# Generated by Terraform — do not edit manually.
# Replica counts for Tesslate deployments.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesslate-backend
  namespace: tesslate
spec:
  replicas: ${backend_replicas}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesslate-frontend
  namespace: tesslate
spec:
  replicas: ${frontend_replicas}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesslate-worker
  namespace: tesslate
spec:
  replicas: ${worker_replicas}
