# Generated by Terraform — do not edit manually.
# Replica counts and resource limits for Tesslate deployments.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesslate-backend
  namespace: tesslate
spec:
  replicas: ${backend_replicas}
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: "${backend_cpu_request}"
              memory: "${backend_memory_request}"
            limits:
              cpu: "${backend_cpu_limit}"
              memory: "${backend_memory_limit}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesslate-frontend
  namespace: tesslate
spec:
  replicas: ${frontend_replicas}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesslate-worker
  namespace: tesslate
spec:
  replicas: ${worker_replicas}
