// ── Element data returned by the bridge ─────────────────────────
export interface ElementData {
  tagName: string;
  id: string;
  classList: string[];
  attributes: Record<string, string>;
  /** Full computed styles — ALL CSS properties */
  computedStyles: Record<string, string>;
  /** Precise bounding rect */
  boundingRect: { top: number; left: number; width: number; height: number };
  /** CSS selector that uniquely identifies this element */
  selector: string;
  /** Truncated to 500 chars */
  innerHTML: string;
  /** Inner text content (visible text only), trimmed, max 500 chars */
  textContent: string;
  /** DOM path from root, e.g. ['html', 'body', 'div.app', 'main'] */
  parentPath: string[];
  /** React component info (null if not React or not detectable) */
  reactComponent: {
    name: string;
    sourceFile?: string;
    lineNumber?: number;
    props?: Record<string, unknown>;
  } | null;
  /** Framework detection */
  framework: 'react' | 'vue' | 'svelte' | 'angular' | 'html' | null;
  /** Box model extracted values */
  boxModel: {
    margin: { top: string; right: string; bottom: string; left: string };
    padding: { top: string; right: string; bottom: string; left: string };
    border: { top: string; right: string; bottom: string; left: string };
    width: string;
    height: string;
  };
  /** Runtime ID assigned by bridge (data-did attribute) */
  designId: string;
}

// ── Message types from parent to iframe ─────────────────────────
export type DesignParentMessage =
  | { type: 'design:activate' }
  | { type: 'design:deactivate' }
  | { type: 'design:inspect'; x: number; y: number; click?: boolean }
  | { type: 'design:update-style'; designId: string; property: string; value: string }
  | { type: 'design:remove-style'; designId: string; property: string }
  | { type: 'design:update-classes'; designId: string; classes: string[] }
  | { type: 'design:insert-element'; parentDesignId: string; tag: string; attributes?: Record<string, string> }
  | { type: 'design:highlight'; selector: string }
  | { type: 'design:clear-highlight' }
  | { type: 'design:set-mode'; mode: 'select' | 'text' | 'move' }
  | { type: 'design:start-text-edit'; designId: string }
  | { type: 'design:stop-text-edit' };

// ── Message types from iframe to parent ─────────────────────────
export type DesignBridgeMessage =
  | { type: 'design:bridge-ready'; framework: string | null }
  | { type: 'design:element-data'; data: ElementData }
  | { type: 'design:hover-data'; data: ElementData }
  | { type: 'design:style-applied'; designId: string; property: string; value: string }
  | { type: 'design:element-inserted'; parentDesignId: string; newDesignId: string }
  | { type: 'design:text-changed'; designId: string; text: string; sourceFile?: string; lineNumber?: number }
  | { type: 'design:element-moved'; designId: string; deltaX: number; deltaY: number }
  | { type: 'design:source-location'; designId: string; sourceFile: string; lineNumber: number };

// ── Bridge script IIFE (written to project public/ as __tesslate-design-bridge.js) ──
export const BRIDGE_SCRIPT_CONTENT: string = [
'(function() {',
'  if (window.__designBridgeActive) return;',
'  window.__designBridgeActive = true;',
'',
'  var overlay = null;',
'  var highlightBox = null;',
'  var labelBox = null;',
'  var selectedElement = null;',
'  var hoveredElement = null;',
'  var active = false;',
'  var designIdCounter = 0;',
'  var styleSheet = null;',
'  var currentMode = "select";',
'  var dragState = null;',
'  var textEditElement = null;',
'',
'  // ── Runtime Element ID System ──────────────────────────────────',
'',
'  function getOrAssignDesignId(el) {',
'    if (!el) return "";',
'    var existing = el.getAttribute("data-did");',
'    if (existing) return existing;',
'    designIdCounter += 1;',
'    var id = "d-" + designIdCounter;',
'    el.setAttribute("data-did", id);',
'    return id;',
'  }',
'',
'  // ── React Fiber Detection (mcp-pointer approach) ──────────────',
'',
'  function getReactFiber(element) {',
'    var keys = Object.keys(element);',
'    for (var i = 0; i < keys.length; i++) {',
'      if (keys[i].indexOf("__reactFiber$") === 0 || keys[i].indexOf("__reactInternalInstance$") === 0) {',
'        return element[keys[i]];',
'      }',
'    }',
'    return null;',
'  }',
'',
'  function getReactComponentInfo(element) {',
'    var fiber = getReactFiber(element);',
'    if (!fiber) return null;',
'    var current = fiber;',
'    while (current) {',
'      if (current.type && typeof current.type === "function") {',
'        var name = current.type.displayName || current.type.name || "Anonymous";',
'        var source = current._debugSource;',
'        var props = {};',
'        if (current.memoizedProps) {',
'          var propKeys = Object.keys(current.memoizedProps);',
'          for (var j = 0; j < propKeys.length; j++) {',
'            var v = current.memoizedProps[propKeys[j]];',
'            if (typeof v !== "function" && typeof v !== "object") props[propKeys[j]] = v;',
'          }',
'        }',
'        return {',
'          name: name,',
'          sourceFile: source ? source.fileName : undefined,',
'          lineNumber: source ? source.lineNumber : undefined,',
'          props: props',
'        };',
'      }',
'      current = current.return;',
'    }',
'    return null;',
'  }',
'',
'  // ── Framework Detection ───────────────────────────────────────',
'',
'  function detectFramework() {',
'    try {',
'      if (document.querySelector("[data-reactroot]") ||',
'          document.getElementById("__next") ||',
'          Object.keys(document.body || {}).some(function(k) { return k.indexOf("__reactFiber") === 0; })) {',
'        return "react";',
'      }',
'      if (document.querySelector("[data-v-]") || window.__VUE__) return "vue";',
'      if (document.querySelector("[class*=\\"svelte-\\"]")) return "svelte";',
'      if (document.querySelector("[ng-version]") || document.querySelector("[_ngcontent]")) return "angular";',
'    } catch (e) { /* ignore */ }',
'    return "html";',
'  }',
'',
'  // ── Shadow DOM Crawling (Onlook approach) ─────────────────────',
'',
'  function getDeepElement(x, y) {',
'    var el = document.elementFromPoint(x, y);',
'    if (!el) return null;',
'    function crawlShadows(node) {',
'      if (node && node.shadowRoot) {',
'        var potential = node.shadowRoot.elementFromPoint(x, y);',
'        if (potential === node) return node;',
'        if (potential && potential.shadowRoot) return crawlShadows(potential);',
'        return potential || node;',
'      }',
'      return node;',
'    }',
'    return crawlShadows(el);',
'  }',
'',
'  // ── Full Computed Style Extraction (mcp-pointer) ──────────────',
'',
'  function getAllComputedStyles(el) {',
'    var computed = window.getComputedStyle(el);',
'    var styles = {};',
'    for (var i = 0; i < computed.length; i++) {',
'      var prop = computed[i];',
'      styles[prop] = computed.getPropertyValue(prop);',
'    }',
'    return styles;',
'  }',
'',
'  // ── CSS Selector Generation ───────────────────────────────────',
'',
'  function generateSelector(el) {',
'    if (!el || el === document.body || el === document.documentElement) return "body";',
'    if (el.id) return "#" + CSS.escape(el.id);',
'    var path = [];',
'    var current = el;',
'    while (current && current !== document.body && current !== document.documentElement) {',
'      var tag = current.tagName.toLowerCase();',
'      if (current.id) {',
'        path.unshift("#" + CSS.escape(current.id));',
'        break;',
'      }',
'      var parent = current.parentElement;',
'      if (parent) {',
'        var siblings = [];',
'        var children = parent.children;',
'        for (var si = 0; si < children.length; si++) {',
'          if (children[si].tagName === current.tagName) siblings.push(children[si]);',
'        }',
'        if (siblings.length > 1) {',
'          var idx = -1;',
'          for (var sj = 0; sj < siblings.length; sj++) {',
'            if (siblings[sj] === current) { idx = sj + 1; break; }',
'          }',
'          if (idx > 0) tag += ":nth-of-type(" + idx + ")";',
'        }',
'      }',
'      path.unshift(tag);',
'      current = current.parentElement;',
'    }',
'    return path.join(" > ") || "body";',
'  }',
'',
'  // ── Box Model Extraction ──────────────────────────────────────',
'',
'  function extractBoxModel(computed) {',
'    return {',
'      margin: {',
'        top: computed.getPropertyValue("margin-top"),',
'        right: computed.getPropertyValue("margin-right"),',
'        bottom: computed.getPropertyValue("margin-bottom"),',
'        left: computed.getPropertyValue("margin-left")',
'      },',
'      padding: {',
'        top: computed.getPropertyValue("padding-top"),',
'        right: computed.getPropertyValue("padding-right"),',
'        bottom: computed.getPropertyValue("padding-bottom"),',
'        left: computed.getPropertyValue("padding-left")',
'      },',
'      border: {',
'        top: computed.getPropertyValue("border-top-width"),',
'        right: computed.getPropertyValue("border-right-width"),',
'        bottom: computed.getPropertyValue("border-bottom-width"),',
'        left: computed.getPropertyValue("border-left-width")',
'      },',
'      width: computed.getPropertyValue("width"),',
'      height: computed.getPropertyValue("height")',
'    };',
'  }',
'',
'  // ── Parent Path Construction ──────────────────────────────────',
'',
'  function getParentPath(el) {',
'    var path = [];',
'    var current = el;',
'    while (current && current !== document) {',
'      var tag = current.tagName.toLowerCase();',
'      if (current.classList && current.classList.length > 0) {',
'        var classes = [];',
'        for (var ci = 0; ci < current.classList.length; ci++) {',
'          classes.push(current.classList[ci]);',
'        }',
'        tag += "." + classes.join(".");',
'      }',
'      path.unshift(tag);',
'      current = current.parentElement;',
'    }',
'    return path;',
'  }',
'',
'  // ── Gather Element Data ───────────────────────────────────────',
'',
'  function gatherElementData(el) {',
'    if (!el || el === document.documentElement || el === document.body) {',
'      el = document.body;',
'    }',
'',
'    var did = getOrAssignDesignId(el);',
'    var rect = el.getBoundingClientRect();',
'    var computed = window.getComputedStyle(el);',
'    var attrs = {};',
'    for (var i = 0; i < el.attributes.length; i++) {',
'      var a = el.attributes[i];',
'      attrs[a.name] = a.value;',
'    }',
'',
'    var inner = el.innerHTML || "";',
'    if (inner.length > 500) inner = inner.substring(0, 500);',
'',
'    var text = (el.textContent || "").replace(/^\\s+|\\s+$/g, "");',
'    if (text.length > 500) text = text.substring(0, 500);',
'',
'    var classList = [];',
'    if (el.classList) {',
'      for (var j = 0; j < el.classList.length; j++) {',
'        classList.push(el.classList[j]);',
'      }',
'    }',
'',
'    return {',
'      tagName: el.tagName.toLowerCase(),',
'      id: el.id || "",',
'      classList: classList,',
'      attributes: attrs,',
'      computedStyles: getAllComputedStyles(el),',
'      boundingRect: { top: rect.top, left: rect.left, width: rect.width, height: rect.height },',
'      selector: generateSelector(el),',
'      innerHTML: inner,',
'      textContent: text,',
'      parentPath: getParentPath(el),',
'      reactComponent: getReactComponentInfo(el),',
'      framework: detectFramework(),',
'      boxModel: extractBoxModel(computed),',
'      designId: did',
'    };',
'  }',
'',
'  // ── Helper: check if element is a bridge overlay element ──────',
'',
'  function isBridgeElement(el) {',
'    if (!el) return false;',
'    return el.hasAttribute && el.hasAttribute("data-tesslate-bridge");',
'  }',
'',
'  // ── Element at Point (shadow DOM + overlay hiding) ────────────',
'',
'  function elementAtPoint(x, y) {',
'    if (overlay) overlay.style.display = "none";',
'    if (highlightBox) highlightBox.style.display = "none";',
'    if (labelBox) labelBox.style.display = "none";',
'    var el = getDeepElement(x, y);',
'    if (overlay) overlay.style.display = "";',
'    if (highlightBox) highlightBox.style.display = "";',
'    if (labelBox) labelBox.style.display = "";',
'    if (isBridgeElement(el)) return null;',
'    return el;',
'  }',
'',
'  // ── Live Style Editing (Onlook CSSManager approach) ───────────',
'',
'  function ensureStyleSheet() {',
'    if (styleSheet) return styleSheet;',
'    var existing = document.getElementById("__design-bridge-styles");',
'    if (existing) {',
'      styleSheet = existing;',
'      return styleSheet;',
'    }',
'    styleSheet = document.createElement("style");',
'    styleSheet.id = "__design-bridge-styles";',
'    styleSheet.setAttribute("data-tesslate-bridge", "1");',
'    document.head.appendChild(styleSheet);',
'    return styleSheet;',
'  }',
'',
'  function updateStyleProperty(designId, property, value) {',
'    var sheet = ensureStyleSheet();',
'    var selector = "[data-did=\\"" + designId + "\\"]";',
'    var rules = sheet.textContent || "";',
'    var re = new RegExp(selector.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&") + "\\\\s*\\\\{([^}]*)\\\\}");',
'    var match = rules.match(re);',
'    if (match) {',
'      var existing = match[1];',
'      var propRe = new RegExp("(^|;)\\\\s*" + property.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&") + "\\\\s*:[^;]*");',
'      if (propRe.test(existing)) {',
'        existing = existing.replace(propRe, "$1 " + property + ": " + value);',
'      } else {',
'        existing = existing + " " + property + ": " + value + ";";',
'      }',
'      sheet.textContent = rules.replace(re, selector + " {" + existing + "}");',
'    } else {',
'      sheet.textContent = rules + "\\n" + selector + " { " + property + ": " + value + "; }";',
'    }',
'  }',
'',
'  function removeStyleProperty(designId, property) {',
'    var sheet = ensureStyleSheet();',
'    var selector = "[data-did=\\"" + designId + "\\"]";',
'    var rules = sheet.textContent || "";',
'    var re = new RegExp(selector.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&") + "\\\\s*\\\\{([^}]*)\\\\}");',
'    var match = rules.match(re);',
'    if (match) {',
'      var existing = match[1];',
'      var propRe = new RegExp("\\\\s*" + property.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&") + "\\\\s*:[^;]*;?");',
'      existing = existing.replace(propRe, "");',
'      if (existing.replace(/\\s/g, "").length === 0) {',
'        sheet.textContent = rules.replace(re, "");',
'      } else {',
'        sheet.textContent = rules.replace(re, selector + " {" + existing + "}");',
'      }',
'    }',
'  }',
'',
'  // ── Overlay & Highlight Rendering ─────────────────────────────',
'',
'  function createOverlay() {',
'    if (overlay) return;',
'    overlay = document.createElement("div");',
'    overlay.setAttribute("data-tesslate-bridge", "1");',
'    overlay.style.cssText = "position:fixed;top:0;left:0;right:0;bottom:0;z-index:2147483646;pointer-events:auto;cursor:crosshair;";',
'',
'    overlay.addEventListener("mousemove", function(e) {',
'      if (!active) return;',
'      if (currentMode === "move" && dragState) {',
'        var dx = e.clientX - dragState.startX;',
'        var dy = e.clientY - dragState.startY;',
'        dragState.el.style.left = (dragState.origLeft + dx) + "px";',
'        dragState.el.style.top = (dragState.origTop + dy) + "px";',
'        var dr = dragState.el.getBoundingClientRect();',
'        showHighlight(dr, true, gatherElementData(dragState.el));',
'        return;',
'      }',
'      var target = elementAtPoint(e.clientX, e.clientY);',
'      if (target && target !== hoveredElement) {',
'        hoveredElement = target;',
'        var r = target.getBoundingClientRect();',
'        showHighlight(r, false, gatherElementData(target));',
'        window.parent.postMessage({',
'          type: "design:hover-data",',
'          data: gatherElementData(target)',
'        }, "*");',
'      }',
'    });',
'',
'    overlay.addEventListener("mousedown", function(e) {',
'      if (!active || currentMode !== "move") return;',
'      var target = elementAtPoint(e.clientX, e.clientY);',
'      if (!target) return;',
'      e.preventDefault();',
'      e.stopPropagation();',
'      var computed = window.getComputedStyle(target);',
'      if (computed.position === "static") {',
'        target.style.position = "relative";',
'      }',
'      var origLeft = parseFloat(target.style.left) || 0;',
'      var origTop = parseFloat(target.style.top) || 0;',
'      dragState = {',
'        el: target,',
'        startX: e.clientX,',
'        startY: e.clientY,',
'        origLeft: origLeft,',
'        origTop: origTop',
'      };',
'      document.body.style.cursor = "grabbing";',
'    });',
'',
'    overlay.addEventListener("mouseup", function(e) {',
'      if (!active || currentMode !== "move" || !dragState) return;',
'      e.preventDefault();',
'      e.stopPropagation();',
'      var finalDx = e.clientX - dragState.startX;',
'      var finalDy = e.clientY - dragState.startY;',
'      var did = getOrAssignDesignId(dragState.el);',
'      updateStyleProperty(did, "position", dragState.el.style.position);',
'      updateStyleProperty(did, "left", dragState.el.style.left);',
'      updateStyleProperty(did, "top", dragState.el.style.top);',
'      window.parent.postMessage({',
'        type: "design:element-moved",',
'        designId: did,',
'        deltaX: finalDx,',
'        deltaY: finalDy',
'      }, "*");',
'      dragState = null;',
'      document.body.style.cursor = "";',
'    });',
'',
'    overlay.addEventListener("click", function(e) {',
'      if (!active) return;',
'      e.preventDefault();',
'      e.stopPropagation();',
'      var target = elementAtPoint(e.clientX, e.clientY);',
'      if (!target) return;',
'',
'      if (currentMode === "text") {',
'        beginTextEdit(target);',
'        return;',
'      }',
'',
'      selectedElement = target;',
'      var data = gatherElementData(target);',
'      var r = target.getBoundingClientRect();',
'      showHighlight(r, true, data);',
'      window.parent.postMessage({',
'        type: "design:element-data",',
'        data: data',
'      }, "*");',
'',
'      if (currentMode === "select" && data.reactComponent && data.reactComponent.sourceFile) {',
'        window.parent.postMessage({',
'          type: "design:source-location",',
'          designId: data.designId,',
'          sourceFile: data.reactComponent.sourceFile,',
'          lineNumber: data.reactComponent.lineNumber || 1',
'        }, "*");',
'      }',
'    });',
'',
'    document.body.appendChild(overlay);',
'  }',
'',
'  function removeOverlay() {',
'    if (overlay && overlay.parentNode) {',
'      overlay.parentNode.removeChild(overlay);',
'    }',
'    overlay = null;',
'    hoveredElement = null;',
'    selectedElement = null;',
'    clearHighlight();',
'  }',
'',
'  function clearHighlight() {',
'    if (highlightBox && highlightBox.parentNode) {',
'      highlightBox.parentNode.removeChild(highlightBox);',
'    }',
'    highlightBox = null;',
'    if (labelBox && labelBox.parentNode) {',
'      labelBox.parentNode.removeChild(labelBox);',
'    }',
'    labelBox = null;',
'  }',
'',
'  function showHighlight(rect, selected, elementData) {',
'    clearHighlight();',
'',
'    highlightBox = document.createElement("div");',
'    highlightBox.setAttribute("data-tesslate-bridge", "1");',
'    if (selected) {',
'      highlightBox.style.cssText = "position:fixed;z-index:2147483647;pointer-events:none;border:2px solid rgba(59,130,246,0.8);background:rgba(59,130,246,0.08);transition:all 0.05s ease;";',
'    } else {',
'      highlightBox.style.cssText = "position:fixed;z-index:2147483647;pointer-events:none;border:2px dashed rgba(59,130,246,0.6);background:rgba(59,130,246,0.05);transition:all 0.05s ease;";',
'    }',
'    highlightBox.style.top = rect.top + "px";',
'    highlightBox.style.left = rect.left + "px";',
'    highlightBox.style.width = rect.width + "px";',
'    highlightBox.style.height = rect.height + "px";',
'    document.body.appendChild(highlightBox);',
'',
'    if (elementData) {',
'      showLabel(rect, elementData);',
'    }',
'  }',
'',
'  function showLabel(rect, data) {',
'    if (labelBox && labelBox.parentNode) {',
'      labelBox.parentNode.removeChild(labelBox);',
'    }',
'    labelBox = document.createElement("div");',
'    labelBox.setAttribute("data-tesslate-bridge", "1");',
'',
'    var labelText = "";',
'    if (data.reactComponent && data.reactComponent.name) {',
'      labelText += "<" + data.reactComponent.name + "> ";',
'    }',
'    labelText += data.tagName;',
'    if (data.classList && data.classList.length > 0) {',
'      labelText += "." + data.classList.slice(0, 3).join(".");',
'    }',
'',
'    labelBox.textContent = labelText;',
'    labelBox.style.cssText = "position:fixed;z-index:2147483647;pointer-events:none;background:rgba(59,130,246,0.9);color:white;font:11px/1 monospace;padding:2px 6px;border-radius:3px;white-space:nowrap;max-width:300px;overflow:hidden;text-overflow:ellipsis;";',
'',
'    var labelTop = rect.top - 20;',
'    if (labelTop < 2) {',
'      labelTop = rect.top + rect.height + 4;',
'    }',
'    labelBox.style.top = labelTop + "px";',
'    labelBox.style.left = Math.max(2, rect.left) + "px";',
'    document.body.appendChild(labelBox);',
'  }',
'',
'  // ── Highlight by Selector ─────────────────────────────────────',
'',
'  function highlightBySelector(selector) {',
'    clearHighlight();',
'    try {',
'      var el = document.querySelector(selector);',
'      if (el) {',
'        var rect = el.getBoundingClientRect();',
'        var data = gatherElementData(el);',
'        showHighlight(rect, true, data);',
'      }',
'    } catch (e) { /* invalid selector */ }',
'  }',
'',
'  // ── Element Insertion ─────────────────────────────────────────',
'',
'  function insertElement(parentDesignId, tag, attributes) {',
'    var parent = document.querySelector("[data-did=\\"" + parentDesignId + "\\"]");',
'    if (!parent) return;',
'    var newEl = document.createElement(tag);',
'    if (attributes) {',
'      var keys = Object.keys(attributes);',
'      for (var i = 0; i < keys.length; i++) {',
'        newEl.setAttribute(keys[i], attributes[keys[i]]);',
'      }',
'    }',
'    var newId = getOrAssignDesignId(newEl);',
'    parent.appendChild(newEl);',
'    window.parent.postMessage({',
'      type: "design:element-inserted",',
'      parentDesignId: parentDesignId,',
'      newDesignId: newId',
'    }, "*");',
'  }',
'',
'  // ── Text Editing Helpers ──────────────────────────────────────',
'',
'  function beginTextEdit(el) {',
'    endTextEdit();',
'    if (!el) return;',
'    textEditElement = el;',
'    if (overlay) overlay.style.display = "none";',
'    el.setAttribute("contenteditable", "true");',
'    el.focus();',
'    var selection = window.getSelection();',
'    var range = document.createRange();',
'    range.selectNodeContents(el);',
'    selection.removeAllRanges();',
'    selection.addRange(range);',
'    el.addEventListener("blur", onTextEditBlur);',
'    el.addEventListener("keydown", onTextEditKeydown);',
'  }',
'',
'  function endTextEdit() {',
'    if (!textEditElement) return;',
'    textEditElement.removeEventListener("blur", onTextEditBlur);',
'    textEditElement.removeEventListener("keydown", onTextEditKeydown);',
'    textEditElement.removeAttribute("contenteditable");',
'    if (overlay) overlay.style.display = "";',
'    textEditElement = null;',
'  }',
'',
'  function onTextEditBlur() {',
'    if (!textEditElement) return;',
'    var el = textEditElement;',
'    var did = getOrAssignDesignId(el);',
'    var newText = el.textContent || "";',
'    var sourceFile = undefined;',
'    var lineNumber = undefined;',
'    var reactInfo = getReactComponentInfo(el);',
'    if (reactInfo && reactInfo.sourceFile) {',
'      sourceFile = reactInfo.sourceFile;',
'      lineNumber = reactInfo.lineNumber;',
'    }',
'    window.parent.postMessage({',
'      type: "design:text-changed",',
'      designId: did,',
'      text: newText,',
'      sourceFile: sourceFile,',
'      lineNumber: lineNumber',
'    }, "*");',
'    endTextEdit();',
'  }',
'',
'  function onTextEditKeydown(e) {',
'    if (e.key === "Escape") {',
'      e.preventDefault();',
'      if (textEditElement) textEditElement.blur();',
'    }',
'  }',
'',
'  // ── Mode Management ──────────────────────────────────────────',
'',
'  function setMode(mode) {',
'    endTextEdit();',
'    if (dragState) {',
'      dragState = null;',
'      document.body.style.cursor = "";',
'    }',
'    currentMode = mode;',
'    if (overlay) {',
'      if (mode === "text") {',
'        overlay.style.cursor = "text";',
'      } else if (mode === "move") {',
'        overlay.style.cursor = "grab";',
'      } else {',
'        overlay.style.cursor = "crosshair";',
'      }',
'    }',
'  }',
'',
'  // ── Message Handler ───────────────────────────────────────────',
'',
'  window.addEventListener("message", function(event) {',
'    var msg = event.data;',
'    if (!msg || typeof msg.type !== "string" || msg.type.indexOf("design:") !== 0) return;',
'',
'    switch (msg.type) {',
'      case "design:activate":',
'        active = true;',
'        createOverlay();',
'        break;',
'',
'      case "design:deactivate":',
'        active = false;',
'        removeOverlay();',
'        break;',
'',
'      case "design:inspect":',
'        var target = elementAtPoint(msg.x, msg.y);',
'        if (target) {',
'          if (active) {',
'            var r = target.getBoundingClientRect();',
'            showHighlight(r, false, gatherElementData(target));',
'            window.parent.postMessage({',
'              type: "design:hover-data",',
'              data: gatherElementData(target)',
'            }, "*");',
'          }',
'          if (msg.click) {',
'            selectedElement = target;',
'            var data = gatherElementData(target);',
'            var cr = target.getBoundingClientRect();',
'            showHighlight(cr, true, data);',
'            window.parent.postMessage({',
'              type: "design:element-data",',
'              data: data',
'            }, "*");',
'          }',
'        }',
'        break;',
'',
'      case "design:update-style":',
'        if (msg.property === "textContent") {',
'          var tcEl = document.querySelector("[data-did=\\"" + msg.designId + "\\"]");',
'          if (tcEl) tcEl.textContent = msg.value;',
'        } else if (msg.property.indexOf("attr:") === 0) {',
'          var attrName = msg.property.substring(5);',
'          var attrEl = document.querySelector("[data-did=\\"" + msg.designId + "\\"]");',
'          if (attrEl) {',
'            if (msg.value === "") { attrEl.removeAttribute(attrName); }',
'            else { attrEl.setAttribute(attrName, msg.value); }',
'          }',
'        } else {',
'          updateStyleProperty(msg.designId, msg.property, msg.value);',
'        }',
'        window.parent.postMessage({',
'          type: "design:style-applied",',
'          designId: msg.designId,',
'          property: msg.property,',
'          value: msg.value',
'        }, "*");',
'        break;',
'',
'      case "design:remove-style":',
'        if (msg.property.indexOf("attr:") === 0) {',
'          var rmAttrEl = document.querySelector("[data-did=\\"" + msg.designId + "\\"]");',
'          if (rmAttrEl) rmAttrEl.removeAttribute(msg.property.substring(5));',
'        } else {',
'          removeStyleProperty(msg.designId, msg.property);',
'        }',
'        break;',
'',
'      case "design:update-classes":',
'        var classTarget = document.querySelector("[data-did=\\"" + msg.designId + "\\"]");',
'        if (classTarget) {',
'          classTarget.className = "";',
'          for (var ci = 0; ci < msg.classes.length; ci++) {',
'            classTarget.classList.add(msg.classes[ci]);',
'          }',
'        }',
'        break;',
'',
'      case "design:insert-element":',
'        insertElement(msg.parentDesignId, msg.tag, msg.attributes);',
'        break;',
'',
'      case "design:highlight":',
'        highlightBySelector(msg.selector);',
'        break;',
'',
'      case "design:clear-highlight":',
'        clearHighlight();',
'        break;',
'',
'      case "design:set-mode":',
'        setMode(msg.mode);',
'        break;',
'',
'      case "design:start-text-edit":',
'        var textTarget = document.querySelector("[data-did=\\"" + msg.designId + "\\"]");',
'        if (textTarget) {',
'          beginTextEdit(textTarget);',
'        }',
'        break;',
'',
'      case "design:stop-text-edit":',
'        if (textEditElement) textEditElement.blur();',
'        break;',
'    }',
'  });',
'',
'  // ── Initialization ────────────────────────────────────────────',
'',
'  window.parent.postMessage({',
'    type: "design:bridge-ready",',
'    framework: detectFramework()',
'  }, "*");',
'})();',
].join('\n');

// ── Helper: send a message to the iframe ────────────────────────
export function sendDesignMessage(
  iframe: HTMLIFrameElement,
  msg: DesignParentMessage,
): void {
  iframe.contentWindow?.postMessage(msg, '*');
}

// ── Type guard for messages from the iframe ─────────────────────
export function isDesignBridgeMessage(
  data: unknown,
): data is DesignBridgeMessage {
  if (
    typeof data !== 'object' ||
    data === null ||
    !('type' in data) ||
    typeof (data as { type: unknown }).type !== 'string'
  ) {
    return false;
  }
  const type = (data as { type: string }).type;
  return (
    type === 'design:element-data' ||
    type === 'design:hover-data' ||
    type === 'design:bridge-ready' ||
    type === 'design:style-applied' ||
    type === 'design:element-inserted' ||
    type === 'design:text-changed' ||
    type === 'design:element-moved' ||
    type === 'design:source-location'
  );
}
