apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: tesslate-local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/k8s-data/postgres"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tesslate-projects-pv
  labels:
    type: local
    app: tesslate-projects
spec:
  storageClassName: tesslate-local-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/k8s-data/projects"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    type: local
    app: registry
spec:
  storageClassName: tesslate-local-storage
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/k8s-data/registry"