"""Workspace Data Store service — the built-in per-project KV/document database.

Single source of truth for collection/record CRUD, validation, quotas and
key management. Consumed by ``routers/workspace_data.py`` (HTTP), the
``workspace_data`` agent tool, and the deploy-time key injection.
"""

from .keys import (
    DEPLOY_KEY_NAME,
    MAX_KEYS_PER_PROJECT,
    VALID_KINDS,
    InvalidKeyError,
    count_data_keys,
    create_data_key,
    generate_key,
    get_data_key,
    hash_key,
    list_data_keys,
    resolve_data_key,
    revoke_data_key,
    rotate_deploy_key,
)
from .store import (
    DEFAULT_PAGE_SIZE,
    MAX_COLLECTIONS_PER_PROJECT,
    MAX_PAGE_SIZE,
    MAX_RECORD_BYTES,
    MAX_RECORDS_PER_PROJECT,
    CollectionExistsError,
    CollectionNotFoundError,
    InvalidNameError,
    InvalidRecordError,
    QuotaExceededError,
    RecordNotFoundError,
    WorkspaceDataError,
    collection_record_count,
    create_collection,
    delete_collection,
    delete_record,
    get_collection,
    get_record,
    insert_record,
    list_collections,
    list_records,
    project_record_count,
    require_collection,
    require_record,
    update_collection,
    update_record,
    validate_collection_name,
    validate_record_data,
)

__all__ = [
    "DEFAULT_PAGE_SIZE",
    "DEPLOY_KEY_NAME",
    "MAX_COLLECTIONS_PER_PROJECT",
    "MAX_KEYS_PER_PROJECT",
    "MAX_PAGE_SIZE",
    "MAX_RECORDS_PER_PROJECT",
    "MAX_RECORD_BYTES",
    "VALID_KINDS",
    "CollectionExistsError",
    "CollectionNotFoundError",
    "InvalidKeyError",
    "InvalidNameError",
    "InvalidRecordError",
    "QuotaExceededError",
    "RecordNotFoundError",
    "WorkspaceDataError",
    "collection_record_count",
    "count_data_keys",
    "create_collection",
    "create_data_key",
    "delete_collection",
    "delete_record",
    "generate_key",
    "get_collection",
    "get_data_key",
    "get_record",
    "hash_key",
    "insert_record",
    "list_collections",
    "list_data_keys",
    "list_records",
    "project_record_count",
    "require_collection",
    "require_record",
    "resolve_data_key",
    "revoke_data_key",
    "rotate_deploy_key",
    "update_collection",
    "update_record",
    "validate_collection_name",
    "validate_record_data",
]
