apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesslate-backend
  namespace: tesslate
  labels:
    app: tesslate-backend
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tesslate-backend
      component: backend
  template:
    metadata:
      labels:
        app: tesslate-backend
        component: backend
    spec:
      serviceAccountName: tesslate-backend-sa
      imagePullSecrets:
      - name: docr-secret
      containers:
      - name: backend
        image: registry.digitalocean.com/finetune/tesslate-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tesslate-app-secrets
              key: SECRET_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: tesslate-app-secrets
              key: OPENAI_API_KEY
        - name: ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ALGORITHM
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        - name: OPENAI_API_BASE
          valueFrom:
            secretKeyRef:
              name: tesslate-app-secrets
              key: OPENAI_API_BASE
        - name: OPENAI_MODEL
          valueFrom:
            secretKeyRef:
              name: tesslate-app-secrets
              key: OPENAI_MODEL
        - name: DEV_SERVER_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DEV_SERVER_BASE_URL
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tesslate-app-secrets
              key: DATABASE_URL
        - name: KUBERNETES_NAMESPACE
          value: "tesslate"
        - name: DEPLOYMENT_MODE
          value: "kubernetes"
        - name: CORS_ORIGINS
          valueFrom:
            secretKeyRef:
              name: tesslate-app-secrets
              key: CORS_ORIGINS
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: tesslate-app-secrets
              key: ALLOWED_HOSTS
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 24
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
