# ClusterIssuer for Let's Encrypt certificate issuance
# Supports both HTTP-01 (for regular domains) and DNS-01 (for wildcard domains)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: admin@tesslate.studio
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    # HTTP-01 solver for regular domains (studio-test.tesslate.com, etc.)
    - http01:
        ingress:
          class: nginx
      selector:
        dnsNames:
        - 'studio-test.tesslate.com'
    # DNS-01 solver for wildcard domains (*.studio-test.tesslate.com)
    # Requires Cloudflare API token stored in cloudflare-api-token secret
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsNames:
        - '*.studio-test.tesslate.com'