# ResourceQuota for user environments namespace
# Limits total resources that can be consumed by all user environments
apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-environments-quota
  namespace: tesslate-user-environments
  labels:
    app: tesslate
    tier: user-workloads
spec:
  hard:
    # Total limits across all user environments
    pods: "50"                              # Max 50 user dev environments
    requests.cpu: "20"                      # 20 CPU cores total requested
    requests.memory: 40Gi                   # 40GB memory total requested
    limits.cpu: "40"                        # 40 CPU cores total max
    limits.memory: 80Gi                     # 80GB memory total max
    persistentvolumeclaims: "50"            # Max 50 PVCs
    services: "50"                          # Max 50 services
    count/ingresses.networking.k8s.io: "50" # Max 50 ingresses