apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: tesslate
  labels:
    app: postgres
spec:
  # Use DigitalOcean's default block storage for dynamic provisioning
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi