"""
Download export deployment provider.

Creates ZIP archives from deployment files for direct download.
This provider does not require any credentials and does not interact
with external services.
"""

import io
import logging
import uuid
import zipfile

from ..base import BaseDeploymentProvider, DeploymentConfig, DeploymentFile, DeploymentResult

logger = logging.getLogger(__name__)


class DownloadExportProvider(BaseDeploymentProvider):
    """
    ZIP/download export provider.

    Creates a ZIP archive from deployment files. The actual download URL
    is generated by the router layer - this provider handles archive creation
    and returns the raw bytes in metadata.
    """

    def validate_credentials(self) -> None:
        """No credentials required for download export."""
        pass

    async def test_credentials(self) -> dict:
        """
        No credentials to test - always succeeds.

        Returns:
            Dictionary indicating success.
        """
        return {
            "valid": True,
            "provider": "download",
            "message": "No credentials required for download export",
        }

    async def deploy(
        self, files: list[DeploymentFile], config: DeploymentConfig
    ) -> DeploymentResult:
        """
        Create a ZIP archive from the deployment files.

        Args:
            files: List of files to include in the archive.
            config: Deployment configuration.

        Returns:
            DeploymentResult with ZIP archive data in metadata.
        """
        deployment_id = f"download-{uuid.uuid4().hex[:12]}"

        try:
            if not files:
                return DeploymentResult(
                    success=False,
                    deployment_id=deployment_id,
                    error="No files provided for archive creation",
                    logs=["Archive creation failed: no files to include"],
                )

            zip_buffer = io.BytesIO()

            with zipfile.ZipFile(
                zip_buffer, "w", zipfile.ZIP_DEFLATED, compresslevel=6
            ) as zf:
                project_prefix = self._sanitize_name(config.project_name)
                written_paths: set[str] = set()

                for deployment_file in files:
                    archive_path = f"{project_prefix}/{deployment_file.path}"

                    # Skip duplicate paths
                    if archive_path in written_paths:
                        logger.warning(
                            "Skipping duplicate path in archive: %s", archive_path
                        )
                        continue
                    written_paths.add(archive_path)

                    zf.writestr(archive_path, deployment_file.content)

            zip_data = zip_buffer.getvalue()
            zip_size = len(zip_data)

            logger.info(
                "Created ZIP archive for project %s: %d files, %d bytes",
                config.project_name,
                len(files),
                zip_size,
            )

            return DeploymentResult(
                success=True,
                deployment_id=deployment_id,
                deployment_url=None,
                logs=[
                    f"Archive created with {len(files)} files",
                    f"Archive size: {zip_size} bytes",
                ],
                metadata={
                    "provider": "download",
                    "format": "zip",
                    "size_bytes": zip_size,
                    "file_count": len(files),
                    "download_ready": True,
                    "archive_data": zip_data,
                },
            )

        except zipfile.BadZipFile as e:
            logger.error("ZIP creation failed for %s: %s", config.project_name, e)
            return DeploymentResult(
                success=False,
                deployment_id=deployment_id,
                error=f"Failed to create ZIP archive: {e}",
                logs=[f"Archive creation failed: {e}"],
            )
        except Exception as e:
            logger.error(
                "Unexpected error creating archive for %s: %s",
                config.project_name,
                e,
                exc_info=True,
            )
            return DeploymentResult(
                success=False,
                deployment_id=deployment_id,
                error=f"Archive creation failed: {e}",
                logs=[f"Archive creation failed: {e}"],
            )

    async def get_deployment_status(self, deployment_id: str) -> dict:
        """
        Return static completed status.

        Download exports are immediately complete once created.

        Args:
            deployment_id: The deployment identifier (unused).

        Returns:
            Static completed status dictionary.
        """
        return {
            "status": "completed",
            "provider": "download",
            "message": "Download archive is ready",
        }

    async def delete_deployment(self, deployment_id: str) -> bool:
        """
        Nothing to delete for download exports.

        The archive data is ephemeral and handled by the router layer.

        Args:
            deployment_id: The deployment identifier (unused).

        Returns:
            True (no external resource to clean up).
        """
        return True

    async def get_deployment_logs(self, deployment_id: str) -> list[str]:
        """
        No logs available for download exports.

        Args:
            deployment_id: The deployment identifier (unused).

        Returns:
            Empty list.
        """
        return []
