"""Auto-scaffold a Workspace Data Store SDK helper into newly-created projects.

Drops a correct, canonical client (`lib/opensailData.{ts,py}`) + a
``.env.example`` into the project at creation time, so the AI agent has a
real file to import — not a spec to hallucinate from. Detects the project's
stack from its files and picks the right template. Fully guarded: failure
here never blocks project creation.
"""

from __future__ import annotations

import json
import logging
from typing import Any
from uuid import UUID

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Templates — one per supported stack. Kept inline so the contract lives in
# one place; refresh the skill body in `skills_tesslate.json` to match.
# ---------------------------------------------------------------------------
_NEXTJS_TS = """\
// lib/opensailData.ts — AUTO-GENERATED by Tesslate Studio.
//
// Connects this app to the project's built-in Workspace Data Store.
// The deploy injector wires these env vars on every deploy — both the
// canonical names AND aliases are set, so any of these work:
//
//   Server-side : OPENSAIL_DATA_API_URL   (or OPENSAIL_DATA_URL),
//                 OPENSAIL_DATA_KEY
//   Client      : NEXT_PUBLIC_OPENSAIL_DATA_API_URL  (or NEXT_PUBLIC_OPENSAIL_DATA_URL),
//                 NEXT_PUBLIC_OPENSAIL_DATA_KEY
//
// API shape (NO /collections/ prefix, NO /records suffix):
//   POST   ${URL}/{collection}                 insert  -> 201 { id, data, ... }
//   GET    ${URL}/{collection}?limit=&offset=  list    -> { records, total, limit, offset }
//   GET    ${URL}/{collection}/{record_id}     get one
//   PATCH  ${URL}/{collection}/{record_id}     replace whole document
//   DELETE ${URL}/{collection}/{record_id}     delete  -> 204

export type DataRecord<T extends object = Record<string, unknown>> = {
  id: string;
  collection_id: string;
  data: T;
  created_at: string;
  updated_at: string;
};

export type DataPage<T extends object = Record<string, unknown>> = {
  records: DataRecord<T>[];
  total: number;
  limit: number;
  offset: number;
};

function resolveUrl(...candidates: (string | undefined)[]): string | undefined {
  for (const c of candidates) if (c && c.length > 0) return c.replace(/\\/+$/, '');
  return undefined;
}

// makeClient is LAZY: it doesn't read env vars until a method on the
// returned object is actually called. This is the whole reason the
// auto-scaffold is safe to import even when env vars haven't been
// injected yet (in-cluster dev before container restart, build-time
// during `next build`, SSR for a page that doesn't use the store, etc.).
// Eager evaluation throws at module-load and 500s the entire app — which
// is what we used to ship and what we no longer ship.
function makeClient(getUrl: () => string | undefined, getKey: () => string | undefined, scope: string) {
  function resolve(): { url: string; key: string } {
    const url = getUrl();
    const key = getKey();
    if (!url || !key) {
      throw new Error(
        `Workspace Data ${scope} env vars are missing — this should never happen ` +
        `on a Tesslate Studio container or deploy (the platform auto-injects them). ` +
        `If you see this in production, create at least one collection in the Data ` +
        `tab; if you see this locally outside the platform, set OPENSAIL_DATA_API_URL ` +
        `(or VITE_/NEXT_PUBLIC_ prefixed variants for browsers) and OPENSAIL_DATA_KEY.`
      );
    }
    return { url, key };
  }

  function headers(key: string): Record<string, string> {
    return { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' };
  }

  return {
    insert: async <T extends object>(coll: string, doc: T): Promise<DataRecord<T>> => {
      const { url, key } = resolve();
      const r = await fetch(`${url}/${coll}`, { method: 'POST', headers: headers(key), body: JSON.stringify(doc), cache: 'no-store' });
      if (!r.ok) throw new Error(`insert ${r.status}: ${await r.text()}`);
      return r.json();
    },
    list: async <T extends object>(coll: string, opts: { limit?: number; offset?: number } = {}): Promise<DataPage<T>> => {
      const { url, key } = resolve();
      const qs = new URLSearchParams(
        Object.entries(opts).filter(([, v]) => v !== undefined).map(([k, v]) => [k, String(v)])
      );
      const r = await fetch(`${url}/${coll}?${qs}`, { headers: headers(key), cache: 'no-store' });
      if (!r.ok) throw new Error(`list ${r.status}: ${await r.text()}`);
      return r.json();
    },
    get: async <T extends object>(coll: string, id: string): Promise<DataRecord<T>> => {
      const { url, key } = resolve();
      const r = await fetch(`${url}/${coll}/${id}`, { headers: headers(key), cache: 'no-store' });
      if (!r.ok) throw new Error(`get ${r.status}: ${await r.text()}`);
      return r.json();
    },
    update: async <T extends object>(coll: string, id: string, doc: T): Promise<DataRecord<T>> => {
      const { url, key } = resolve();
      const r = await fetch(`${url}/${coll}/${id}`, { method: 'PATCH', headers: headers(key), body: JSON.stringify(doc), cache: 'no-store' });
      if (!r.ok) throw new Error(`update ${r.status}: ${await r.text()}`);
      return r.json();
    },
    delete: async (coll: string, id: string): Promise<boolean> => {
      const { url, key } = resolve();
      const r = await fetch(`${url}/${coll}/${id}`, { method: 'DELETE', headers: headers(key), cache: 'no-store' });
      return r.ok;
    },
  };
}

/** Server-side client — use in Route Handlers, Server Actions, server components. */
export const serverData = makeClient(
  () => resolveUrl(process.env.OPENSAIL_DATA_API_URL, process.env.OPENSAIL_DATA_URL),
  () => process.env.OPENSAIL_DATA_KEY,
  'server',
);

/** Browser client — use in 'use client' components. */
export const browserData = makeClient(
  () => resolveUrl(
    process.env.NEXT_PUBLIC_OPENSAIL_DATA_API_URL,
    process.env.NEXT_PUBLIC_OPENSAIL_DATA_URL,
  ),
  () => process.env.NEXT_PUBLIC_OPENSAIL_DATA_KEY,
  'browser',
);
"""


_VITE_TS = """\
// src/lib/opensailData.ts
// AUTO-GENERATED by Tesslate Studio.
//
// Connects this app to the project's built-in Workspace Data Store.
// The deploy injector wires these env vars on every deploy — DO NOT rename:
//   VITE_OPENSAIL_DATA_API_URL, VITE_OPENSAIL_DATA_KEY
//
// API shape (NO /collections/ prefix, NO /records suffix):
//   POST   ${URL}/{collection}                 insert
//   GET    ${URL}/{collection}?limit=&offset=  list
//   GET    ${URL}/{collection}/{record_id}     get one
//   PATCH  ${URL}/{collection}/{record_id}     replace
//   DELETE ${URL}/{collection}/{record_id}     delete

export type DataRecord<T extends object = Record<string, unknown>> = {
  id: string;
  collection_id: string;
  data: T;
  created_at: string;
  updated_at: string;
};

export type DataPage<T extends object = Record<string, unknown>> = {
  records: DataRecord<T>[];
  total: number;
  limit: number;
  offset: number;
};

// The platform injects both the canonical name AND a `_URL` alias on deploy.
const URL = (import.meta.env.VITE_OPENSAIL_DATA_API_URL ?? import.meta.env.VITE_OPENSAIL_DATA_URL) as string | undefined;
const KEY = import.meta.env.VITE_OPENSAIL_DATA_KEY as string | undefined;

if (!URL || !KEY) {
  console.warn(
    'Workspace Data env vars missing. The platform auto-injects ' +
    'VITE_OPENSAIL_DATA_API_URL and VITE_OPENSAIL_DATA_KEY on deploy — hit Deploy in Tesslate Studio.'
  );
}

const headers = { Authorization: `Bearer ${KEY}`, 'Content-Type': 'application/json' };

export const data = {
  insert: async <T extends object>(coll: string, doc: T): Promise<DataRecord<T>> => {
    const r = await fetch(`${URL}/${coll}`, { method: 'POST', headers, body: JSON.stringify(doc) });
    if (!r.ok) throw new Error(`insert ${r.status}`);
    return r.json();
  },
  list: async <T extends object>(coll: string, opts: { limit?: number; offset?: number } = {}): Promise<DataPage<T>> => {
    const qs = new URLSearchParams(
      Object.entries(opts).filter(([, v]) => v !== undefined).map(([k, v]) => [k, String(v)])
    );
    const r = await fetch(`${URL}/${coll}?${qs}`, { headers });
    if (!r.ok) throw new Error(`list ${r.status}`);
    return r.json();
  },
  get: async <T extends object>(coll: string, id: string): Promise<DataRecord<T>> => {
    const r = await fetch(`${URL}/${coll}/${id}`, { headers });
    if (!r.ok) throw new Error(`get ${r.status}`);
    return r.json();
  },
  update: async <T extends object>(coll: string, id: string, doc: T): Promise<DataRecord<T>> => {
    const r = await fetch(`${URL}/${coll}/${id}`, { method: 'PATCH', headers, body: JSON.stringify(doc) });
    if (!r.ok) throw new Error(`update ${r.status}`);
    return r.json();
  },
  delete: async (coll: string, id: string): Promise<boolean> => {
    const r = await fetch(`${URL}/${coll}/${id}`, { method: 'DELETE', headers });
    return r.ok;
  },
};
"""


_PYTHON_PY = '''\
"""opensail_data.py — server-side client for the Workspace Data Store.

AUTO-GENERATED by Tesslate Studio.

The platform injects these env vars on every deploy — DO NOT rename:
  - OPENSAIL_DATA_API_URL
  - OPENSAIL_DATA_KEY

API shape (NO ``/collections/`` prefix, NO ``/records`` suffix):
  POST   {URL}/{collection}                 insert
  GET    {URL}/{collection}?limit=&offset=  list
  GET    {URL}/{collection}/{record_id}     get one
  PATCH  {URL}/{collection}/{record_id}     replace
  DELETE {URL}/{collection}/{record_id}     delete
"""

import os
from typing import Any

import httpx

# The platform injects both the canonical name AND a _URL alias on deploy.
URL = os.environ.get("OPENSAIL_DATA_API_URL") or os.environ.get("OPENSAIL_DATA_URL") or ""
KEY = os.environ.get("OPENSAIL_DATA_KEY", "")

if not URL or not KEY:
    raise RuntimeError(
        "Workspace Data env vars are missing. The platform auto-injects "
        "OPENSAIL_DATA_API_URL + OPENSAIL_DATA_KEY on deploy — hit Deploy in Tesslate Studio."
    )

_client = httpx.Client(headers={"Authorization": f"Bearer {KEY}"}, timeout=30.0)


def insert(collection: str, doc: dict[str, Any]) -> dict[str, Any]:
    r = _client.post(f"{URL}/{collection}", json=doc)
    r.raise_for_status()
    return r.json()


def list_records(collection: str, *, limit: int = 50, offset: int = 0) -> dict[str, Any]:
    r = _client.get(f"{URL}/{collection}", params={"limit": limit, "offset": offset})
    r.raise_for_status()
    return r.json()  # {"records": [...], "total": N, "limit": N, "offset": N}


def get(collection: str, record_id: str) -> dict[str, Any]:
    r = _client.get(f"{URL}/{collection}/{record_id}")
    r.raise_for_status()
    return r.json()


def update(collection: str, record_id: str, doc: dict[str, Any]) -> dict[str, Any]:
    r = _client.patch(f"{URL}/{collection}/{record_id}", json=doc)
    r.raise_for_status()
    return r.json()


def delete(collection: str, record_id: str) -> None:
    r = _client.delete(f"{URL}/{collection}/{record_id}")
    r.raise_for_status()
'''


_NEXTJS_ENV = """\
# Tesslate Studio injects these env vars on every deploy — DO NOT commit
# real values. For local dev you can paste an anon key from the Data tab.

# Server-side (Route Handlers, Server Actions, server components)
OPENSAIL_DATA_API_URL=
OPENSAIL_DATA_KEY=

# Browser (Next.js client components — must use NEXT_PUBLIC_ prefix)
NEXT_PUBLIC_OPENSAIL_DATA_API_URL=
NEXT_PUBLIC_OPENSAIL_DATA_KEY=
"""


_VITE_ENV = """\
# Tesslate Studio injects these env vars on every deploy.
# For local dev, paste an anon key from the Data tab.
VITE_OPENSAIL_DATA_API_URL=
VITE_OPENSAIL_DATA_KEY=
"""


_PYTHON_ENV = """\
# Tesslate Studio injects these env vars on every deploy.
OPENSAIL_DATA_API_URL=
OPENSAIL_DATA_KEY=
"""


_GENERIC_README = """\
# Workspace Data Store

This project has a built-in datastore. On every deploy, Tesslate Studio
auto-injects these environment variables — use them, don't rename them:

| Runtime | URL var | KEY var |
|---|---|---|
| Server (Node, Python, Go) | `OPENSAIL_DATA_API_URL` | `OPENSAIL_DATA_KEY` |
| Vite-built frontend (browser) | `VITE_OPENSAIL_DATA_API_URL` | `VITE_OPENSAIL_DATA_KEY` |
| Next.js client components | `NEXT_PUBLIC_OPENSAIL_DATA_API_URL` | `NEXT_PUBLIC_OPENSAIL_DATA_KEY` |

## HTTP API (NO `/collections/` prefix, NO `/records` suffix)

```
POST   ${URL}/{collection}                 insert  -> 201 { id, data, ... }
GET    ${URL}/{collection}?limit=&offset=  list    -> { records, total, limit, offset }
GET    ${URL}/{collection}/{record_id}     get one
PATCH  ${URL}/{collection}/{record_id}     replace
DELETE ${URL}/{collection}/{record_id}     delete  -> 204
```

All requests need `Authorization: Bearer ${KEY}`. JSON body for POST/PATCH.

## curl

```bash
curl -X POST "$OPENSAIL_DATA_API_URL/submissions" \\
  -H "Authorization: Bearer $OPENSAIL_DATA_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"email":"a@b.com","message":"hi"}'
```

## Limits
- Collection names: `^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$`
- Record size: 64 KB max
- Per project: 50 collections, 10000 records, 20 keys
- Pagination `limit`: default 50, max 200
"""


# ---------------------------------------------------------------------------
# Stack detection + file scaffold
# ---------------------------------------------------------------------------
async def _read(orchestrator, project, user_id: UUID, path: str) -> str | None:
    try:
        return await orchestrator.read_file(
            user_id=user_id,
            project_id=project.id,
            container_name=None,
            file_path=path,
            project_slug=project.slug,
            volume_id=getattr(project, "volume_id", None),
            cache_node=getattr(project, "cache_node", None),
        )
    except Exception:
        return None


async def _detect_stack(orchestrator, project, user_id: UUID) -> str:
    """Return one of: 'nextjs', 'vite', 'plain_js', 'python', 'empty'."""
    pkg = await _read(orchestrator, project, user_id, "package.json")
    if pkg:
        try:
            data = json.loads(pkg)
            deps = {**(data.get("dependencies") or {}), **(data.get("devDependencies") or {})}
            if "next" in deps:
                return "nextjs"
            if "vite" in deps:
                return "vite"
            return "plain_js"
        except json.JSONDecodeError:
            pass
    for marker in ("pyproject.toml", "requirements.txt"):
        if await _read(orchestrator, project, user_id, marker):
            return "python"
    return "empty"


_FILES_PER_STACK: dict[str, list[tuple[str, str]]] = {
    "nextjs": [("lib/opensailData.ts", _NEXTJS_TS), (".env.example", _NEXTJS_ENV)],
    "vite": [("src/lib/opensailData.ts", _VITE_TS), (".env.example", _VITE_ENV)],
    "plain_js": [("lib/opensailData.ts", _NEXTJS_TS), (".env.example", _NEXTJS_ENV)],
    "python": [("opensail_data.py", _PYTHON_PY), (".env.example", _PYTHON_ENV)],
    "empty": [("OPENSAIL_DATA.md", _GENERIC_README)],
}


async def scaffold_workspace_data(project: Any, user_id: UUID, settings: Any) -> None:
    """Drop the Workspace Data SDK helper(s) into the project.

    Detects the stack from project files and writes the language-appropriate
    SDK + ``.env.example`` (or a generic README for empty workspaces). Skips
    any file that already exists so we never overwrite the user's edits or
    files baked into the base. Fully guarded — never raises.
    """
    try:
        from .orchestration import get_orchestrator

        orchestrator = get_orchestrator()
        stack = await _detect_stack(orchestrator, project, user_id)
        files = _FILES_PER_STACK.get(stack, _FILES_PER_STACK["empty"])
        for path, content in files:
            if await _read(orchestrator, project, user_id, path) is not None:
                logger.info(
                    "[ws-data-scaffold] %s already exists in project %s, skipping",
                    path,
                    project.id,
                )
                continue
            try:
                await orchestrator.write_file(
                    user_id=user_id,
                    project_id=project.id,
                    container_name=None,
                    file_path=path,
                    content=content,
                    project_slug=project.slug,
                    volume_id=getattr(project, "volume_id", None),
                    cache_node=getattr(project, "cache_node", None),
                )
                logger.info(
                    "[ws-data-scaffold] wrote %s for project %s (stack=%s)",
                    path,
                    project.id,
                    stack,
                )
            except Exception as exc:
                logger.warning(
                    "[ws-data-scaffold] write %s failed for project %s: %s",
                    path,
                    project.id,
                    exc,
                )
    except Exception as exc:
        logger.warning(
            "[ws-data-scaffold] failed for project %s: %s",
            getattr(project, "id", "?"),
            exc,
        )
