apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: tesslate-registry
  labels:
    app: docker-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
    name: registry