apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: tesslate-registry
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      tls:
        certificate: /etc/ssl/certs/tls.crt
        key: /etc/ssl/private/tls.key