"""Hard reset for the OpenSail Automation Runtime + App Runtime Contract.

Revision ID: 0074_hard_reset
Revises: 0073_spend_attribution
Create Date: 2026-04-26

Phase 1 of the OpenSail Automation Runtime rollout.

Per the v8 plan ("no compat layer, wipe today's user state"), this is the
load-bearing migration that:

1. Deletes dependent rows that point at the legacy tables we are about
   to drop (``app_instances``, ``agent_schedules``, etc.).
2. Drops the legacy FK constraints from those dependent tables, then
   drops the legacy tables themselves.
3. Renames ``projects.app_role`` to ``projects.project_kind`` and
   normalizes the value set into the new vocabulary
   (``workspace`` | ``app_source`` | ``app_runtime``).
4. Creates the new ``automation_*`` and ``app_*`` projection tables.
5. Recreates ``app_instances`` and ``app_install_attempts`` in their new
   shape (adds ``runtime_deployment_id`` reserved for Phase 3).
6. Re-attaches FK constraints from ``spend_records``,
   ``mcp_consent_records`` and ``litellm_key_ledger`` back to the
   recreated ``app_instances``, plus the new
   ``spend_records.automation_run_id`` FK to ``automation_runs``.

The migration is intentionally non-reversible: ``downgrade()`` drops the
new tables and reverses the column rename only — it makes no attempt to
rebuild the wiped user state.

Portable across Postgres (cloud) and SQLite (desktop sidecar) via
``op.batch_alter_table`` for the FK alters that SQLite cannot do in place.

For background see plan
``/Users/smirk/.claude/plans/ultrathink-i-want-to-glittery-pond.md``,
sections "Architecture & Primitives" and "Hard Reset Migration".
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.types.guid import GUID

# revision identifiers, used by Alembic.
revision: str = "0074_hard_reset"
down_revision: str | Sequence[str] | None = "0073_spend_attribution"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def _is_sqlite() -> bool:
    return op.get_bind().dialect.name == "sqlite"


def _drop_fks_to(table_name: str, target_table: str) -> None:
    """Drop every FK on ``table_name`` that targets ``target_table``.

    FK names were auto-generated by SQLAlchemy in earlier migrations, so
    we look them up via the dialect inspector instead of hardcoding.
    Operates inside a ``batch_alter_table`` so SQLite gets table-rebuild
    semantics while Postgres just emits ALTER TABLE.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if table_name not in inspector.get_table_names():
        return
    fks = inspector.get_foreign_keys(table_name)
    matching = [fk for fk in fks if fk.get("referred_table") == target_table]
    if not matching:
        return
    with op.batch_alter_table(table_name) as batch_op:
        for fk in matching:
            name = fk.get("name")
            if not name:
                continue
            batch_op.drop_constraint(name, type_="foreignkey")


# JSONB on Postgres, JSON on SQLite — match the existing convention used
# everywhere else in this alembic chain.
def _json_col() -> sa.types.TypeEngine:
    return postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite")


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    # -----------------------------------------------------------------
    # STEP 1 — delete dependent rows that reference legacy tables.
    # -----------------------------------------------------------------
    # ``agent_steps.schedule_id`` does not exist in the current schema
    # (verified against models.py / migrations 0001..0073), so nothing
    # to delete there. Guard defensively in case a downstream branch
    # added one.
    if "agent_steps" in existing_tables:
        agent_steps_cols = {c["name"] for c in inspector.get_columns("agent_steps")}
        if "schedule_id" in agent_steps_cols:
            op.execute(
                sa.text("DELETE FROM agent_steps WHERE schedule_id IS NOT NULL")
            )

    if "mcp_consent_records" in existing_tables:
        op.execute(
            sa.text(
                "DELETE FROM mcp_consent_records WHERE app_instance_id IS NOT NULL"
            )
        )
    if "litellm_key_ledger" in existing_tables:
        op.execute(
            sa.text(
                "DELETE FROM litellm_key_ledger "
                "WHERE app_instance_id IS NOT NULL OR session_id IS NOT NULL"
            )
        )
    if "spend_records" in existing_tables:
        op.execute(
            sa.text("DELETE FROM spend_records WHERE app_instance_id IS NOT NULL")
        )
    if "app_install_attempts" in existing_tables:
        op.execute(sa.text("DELETE FROM app_install_attempts"))
    if "schedule_trigger_events" in existing_tables:
        op.execute(sa.text("DELETE FROM schedule_trigger_events"))

    # -----------------------------------------------------------------
    # STEP 2 — drop FKs from dependents to soon-to-be-dropped tables.
    # -----------------------------------------------------------------
    # FK names are auto-generated; the helper inspects and drops them
    # by inspector lookup so we are not coupled to SQLAlchemy's naming.
    _drop_fks_to("mcp_consent_records", "app_instances")
    _drop_fks_to("litellm_key_ledger", "app_instances")
    _drop_fks_to("spend_records", "app_instances")
    _drop_fks_to("app_install_attempts", "app_instances")
    _drop_fks_to("app_install_attempts", "marketplace_apps")
    _drop_fks_to("app_install_attempts", "app_versions")
    _drop_fks_to("app_install_attempts", "users")
    _drop_fks_to("agent_schedules", "app_instances")
    _drop_fks_to("schedule_trigger_events", "agent_schedules")

    # -----------------------------------------------------------------
    # STEP 3 — drop legacy tables.
    # -----------------------------------------------------------------
    # SQLite has no CASCADE; once FKs are gone, plain DROP works on both.
    if "schedule_trigger_events" in existing_tables:
        op.drop_table("schedule_trigger_events")
    if "agent_schedules" in existing_tables:
        op.drop_table("agent_schedules")
    if "app_install_attempts" in existing_tables:
        op.drop_table("app_install_attempts")
    if "app_instances" in existing_tables:
        # uq_app_instance_project_installed is a partial unique index on
        # Postgres; drop_table cleans it up automatically.
        op.drop_table("app_instances")

    # -----------------------------------------------------------------
    # STEP 4 — rename projects.app_role → projects.project_kind, and
    #          normalize the value set.
    # -----------------------------------------------------------------
    # Drop the existing index on app_role first so the rename is clean
    # and we can re-create the index against the new column name.
    op.drop_index("ix_projects_app_role", table_name="projects")

    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column(
            "app_role",
            new_column_name="project_kind",
            existing_type=sa.String(length=20),
            existing_nullable=False,
            existing_server_default="none",
        )

    # Normalize values: 'none' → 'workspace', NULL → 'workspace',
    # 'app_instance' → 'app_runtime'. 'app_source' rows keep their value.
    op.execute(
        sa.text(
            "UPDATE projects SET project_kind = 'workspace' "
            "WHERE project_kind IS NULL OR project_kind = 'none'"
        )
    )
    op.execute(
        sa.text(
            "UPDATE projects SET project_kind = 'app_runtime' "
            "WHERE project_kind = 'app_instance'"
        )
    )

    # Update the column default to the new vocabulary value.
    with op.batch_alter_table("projects") as batch_op:
        batch_op.alter_column(
            "project_kind",
            existing_type=sa.String(length=20),
            existing_nullable=False,
            server_default="workspace",
        )

    # Add the CHECK constraint via batch so SQLite picks it up on rebuild.
    with op.batch_alter_table("projects") as batch_op:
        batch_op.create_check_constraint(
            "ck_projects_project_kind",
            "project_kind IN ('workspace', 'app_source', 'app_runtime')",
        )

    op.create_index("ix_projects_project_kind", "projects", ["project_kind"])

    # -----------------------------------------------------------------
    # STEP 5 — create automation_* tables.
    # -----------------------------------------------------------------
    op.create_table(
        "automation_definitions",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column(
            "owner_user_id",
            GUID(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "team_id",
            GUID(),
            sa.ForeignKey("teams.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("workspace_scope", sa.String(48), nullable=False, server_default="none"),
        sa.Column(
            "workspace_project_id",
            GUID(),
            sa.ForeignKey("projects.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "target_project_id",
            GUID(),
            sa.ForeignKey("projects.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("contract", _json_col(), nullable=False),
        sa.Column(
            "max_compute_tier", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("max_spend_per_run_usd", sa.Numeric(12, 4), nullable=True),
        sa.Column("max_spend_per_day_usd", sa.Numeric(12, 4), nullable=True),
        sa.Column(
            "parent_automation_id",
            GUID(),
            sa.ForeignKey("automation_definitions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("depth", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column("paused_reason", sa.Text(), nullable=True),
        sa.Column(
            "attribution_user_id",
            GUID(),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_by_user_id",
            GUID(),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_by_automation_id", GUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parent_automation_id IS NULL OR parent_automation_id != id",
            name="ck_automation_definitions_no_self_parent",
        ),
        sa.CheckConstraint(
            "depth IN (0, 1)",
            name="ck_automation_definitions_depth_range",
        ),
        sa.CheckConstraint(
            "workspace_scope <> 'none' OR max_compute_tier = 0",
            name="ck_automation_definitions_scope_none_tier_zero",
        ),
    )
    op.create_index(
        "ix_automation_definitions_owner_active",
        "automation_definitions",
        ["owner_user_id", "is_active"],
    )
    op.create_index(
        "ix_automation_definitions_team_id",
        "automation_definitions",
        ["team_id"],
    )

    op.create_table(
        "automation_triggers",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "automation_id",
            GUID(),
            sa.ForeignKey("automation_definitions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("config", _json_col(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('cron', 'webhook', 'app_invocation', 'manual')",
            name="ck_automation_triggers_kind",
        ),
    )
    op.create_index(
        "ix_automation_triggers_automation_id",
        "automation_triggers",
        ["automation_id"],
    )
    # Cron-only producer index — partial on Postgres, plain on SQLite.
    if _is_postgres():
        op.create_index(
            "ix_automation_triggers_cron_due",
            "automation_triggers",
            ["next_run_at"],
            postgresql_where=sa.text("is_active AND kind = 'cron'"),
        )
    else:
        op.create_index(
            "ix_automation_triggers_cron_due",
            "automation_triggers",
            ["next_run_at"],
        )

    op.create_table(
        "app_actions",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "app_version_id",
            GUID(),
            sa.ForeignKey("app_versions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("handler", _json_col(), nullable=False),
        sa.Column("input_schema", _json_col(), nullable=True),
        sa.Column("output_schema", _json_col(), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=True),
        sa.Column("idempotency", _json_col(), nullable=True),
        sa.Column("billing", _json_col(), nullable=True),
        sa.Column(
            "required_connectors",
            _json_col(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
        sa.Column(
            "required_grants",
            _json_col(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
        sa.Column("result_template", sa.Text(), nullable=True),
        sa.Column(
            "artifacts", _json_col(), nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "app_version_id", "name", name="uq_app_actions_version_name"
        ),
    )
    op.create_index("ix_app_actions_app_version_id", "app_actions", ["app_version_id"])
    op.create_index(
        "ix_app_actions_version_name", "app_actions", ["app_version_id", "name"]
    )

    op.create_table(
        "automation_actions",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "automation_id",
            GUID(),
            sa.ForeignKey("automation_definitions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("ordinal", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("action_type", sa.String(32), nullable=False),
        sa.Column("config", _json_col(), nullable=False),
        sa.Column(
            "app_action_id",
            GUID(),
            sa.ForeignKey("app_actions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action_type IN ('agent.run', 'app.invoke', 'gateway.send')",
            name="ck_automation_actions_action_type",
        ),
    )
    op.create_index(
        "ix_automation_actions_automation_id",
        "automation_actions",
        ["automation_id"],
    )

    op.create_table(
        "automation_events",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "automation_id",
            GUID(),
            sa.ForeignKey("automation_definitions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "trigger_id",
            GUID(),
            sa.ForeignKey("automation_triggers.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "payload", _json_col(), nullable=False, server_default=sa.text("'{}'")
        ),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("trigger_kind", sa.String(16), nullable=False),
    )
    op.create_index(
        "ix_automation_events_automation_received",
        "automation_events",
        ["automation_id", "received_at"],
    )
    # Partial unique on idempotency_key — Postgres uses a true partial
    # index. On SQLite, NULL values are treated as distinct by UNIQUE so
    # a plain unique index is functionally equivalent for the
    # "non-null keys must be unique" guarantee.
    if _is_postgres():
        op.create_index(
            "uq_automation_events_idempotency_key",
            "automation_events",
            ["idempotency_key"],
            unique=True,
            postgresql_where=sa.text("idempotency_key IS NOT NULL"),
        )
    else:
        op.create_index(
            "uq_automation_events_idempotency_key",
            "automation_events",
            ["idempotency_key"],
            unique=True,
        )

    op.create_table(
        "automation_runs",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "automation_id",
            GUID(),
            sa.ForeignKey("automation_definitions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "event_id",
            GUID(),
            sa.ForeignKey("automation_events.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "status", sa.String(32), nullable=False, server_default="queued"
        ),
        sa.Column(
            "retry_count", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("lease_term", sa.Integer(), nullable=True),
        sa.Column("worker_id", sa.Text(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "spend_usd", sa.Numeric(12, 4), nullable=False, server_default="0"
        ),
        sa.Column(
            "spend_by_source",
            _json_col(),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column(
            "contract_breaches", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "approver_user_id",
            GUID(),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("paused_reason", sa.Text(), nullable=True),
        sa.Column("raw_output", _json_col(), nullable=True),
        sa.Column("checkpoint", _json_col(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "automation_id", "event_id", name="uq_automation_runs_automation_event"
        ),
    )
    op.create_index(
        "ix_automation_runs_automation_status",
        "automation_runs",
        ["automation_id", "status"],
    )
    if _is_postgres():
        op.create_index(
            "ix_automation_runs_running_heartbeat",
            "automation_runs",
            ["heartbeat_at"],
            postgresql_where=sa.text("status = 'running'"),
        )
    else:
        op.create_index(
            "ix_automation_runs_running_heartbeat",
            "automation_runs",
            ["heartbeat_at"],
        )

    op.create_table(
        "automation_run_artifacts",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "run_id",
            GUID(),
            sa.ForeignKey("automation_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("storage_mode", sa.String(16), nullable=False),
        sa.Column("storage_ref", sa.Text(), nullable=False),
        sa.Column("preview_text", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "meta", _json_col(), nullable=False, server_default=sa.text("'{}'")
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_automation_run_artifacts_run_id", "automation_run_artifacts", ["run_id"]
    )

    op.create_table(
        "automation_delivery_targets",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "automation_id",
            GUID(),
            sa.ForeignKey("automation_definitions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("destination_id", GUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "on_failure", _json_col(), nullable=False, server_default=sa.text("'{}'")
        ),
        sa.Column(
            "artifact_filter", sa.Text(), nullable=False, server_default="all"
        ),
    )
    op.create_index(
        "ix_automation_delivery_targets_automation_id",
        "automation_delivery_targets",
        ["automation_id"],
    )

    op.create_table(
        "automation_approval_requests",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "run_id",
            GUID(),
            sa.ForeignKey("automation_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "resolved_by_user_id",
            GUID(),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("reason", sa.String(48), nullable=False),
        sa.Column(
            "context", _json_col(), nullable=False, server_default=sa.text("'{}'")
        ),
        sa.Column(
            "context_artifacts",
            _json_col(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
        sa.Column(
            "options", _json_col(), nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column(
            "delivered_to",
            _json_col(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
        sa.Column("response", _json_col(), nullable=True),
    )
    op.create_index(
        "ix_automation_approval_requests_run_id",
        "automation_approval_requests",
        ["run_id"],
    )

    # -----------------------------------------------------------------
    # STEP 6 — create app_* projection tables.
    # (app_actions was created earlier so automation_actions could FK it.)
    # -----------------------------------------------------------------
    op.create_table(
        "app_views",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "app_version_id",
            GUID(),
            sa.ForeignKey("app_versions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("entrypoint", sa.Text(), nullable=False),
        sa.Column("input_schema", _json_col(), nullable=True),
        sa.Column("output_schema", _json_col(), nullable=True),
        sa.Column("cache_ttl_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint("app_version_id", "name", name="uq_app_views_version_name"),
        sa.CheckConstraint(
            "kind IN ('card', 'full_page', 'drawer')", name="ck_app_views_kind"
        ),
    )
    op.create_index("ix_app_views_app_version_id", "app_views", ["app_version_id"])

    op.create_table(
        "app_data_resources",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "app_version_id",
            GUID(),
            sa.ForeignKey("app_versions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "backed_by_action_id",
            GUID(),
            sa.ForeignKey("app_actions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("schema", _json_col(), nullable=True),
        sa.Column("cache_ttl_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "app_version_id", "name", name="uq_app_data_resources_version_name"
        ),
    )
    op.create_index(
        "ix_app_data_resources_app_version_id",
        "app_data_resources",
        ["app_version_id"],
    )

    op.create_table(
        "app_dependencies",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "app_version_id",
            GUID(),
            sa.ForeignKey("app_versions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column(
            "child_app_id",
            GUID(),
            sa.ForeignKey("marketplace_apps.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "required", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column(
            "needs_actions",
            _json_col(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
        sa.Column(
            "needs_views", _json_col(), nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column(
            "needs_data_resources",
            _json_col(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "app_version_id", "alias", name="uq_app_dependencies_version_alias"
        ),
    )
    op.create_index(
        "ix_app_dependencies_app_version_id",
        "app_dependencies",
        ["app_version_id"],
    )

    op.create_table(
        "app_connector_requirements",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "app_version_id",
            GUID(),
            sa.ForeignKey("app_versions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("connector_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column(
            "scopes", _json_col(), nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column("exposure", sa.String(8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "app_version_id",
            "connector_id",
            name="uq_app_connector_requirements_version_connector",
        ),
        sa.CheckConstraint(
            "exposure IN ('proxy', 'env')",
            name="ck_app_connector_requirements_exposure",
        ),
    )
    op.create_index(
        "ix_app_connector_requirements_app_version_id",
        "app_connector_requirements",
        ["app_version_id"],
    )

    op.create_table(
        "app_automation_templates",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "app_version_id",
            GUID(),
            sa.ForeignKey("app_versions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("trigger_config", _json_col(), nullable=False),
        sa.Column("action_config", _json_col(), nullable=False),
        sa.Column(
            "delivery_config",
            _json_col(),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column(
            "contract_template",
            _json_col(),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column(
            "is_default_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "app_version_id", "name", name="uq_app_automation_templates_version_name"
        ),
    )
    op.create_index(
        "ix_app_automation_templates_app_version_id",
        "app_automation_templates",
        ["app_version_id"],
    )

    # -----------------------------------------------------------------
    # STEP 7 — recreate app_instances with the new shape.
    # -----------------------------------------------------------------
    op.create_table(
        "app_instances",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "app_id",
            GUID(),
            sa.ForeignKey("marketplace_apps.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "app_version_id",
            GUID(),
            sa.ForeignKey("app_versions.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "installer_user_id",
            GUID(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            GUID(),
            sa.ForeignKey("projects.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column(
            "state", sa.String(24), nullable=False, server_default="installing"
        ),
        sa.Column(
            "consent_record",
            _json_col(),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column(
            "wallet_mix",
            _json_col(),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column(
            "update_policy", sa.String(16), nullable=False, server_default="manual"
        ),
        sa.Column("volume_id", sa.Text(), nullable=True),
        sa.Column("feature_set_hash", sa.Text(), nullable=True),
        sa.Column(
            "primary_container_id",
            GUID(),
            sa.ForeignKey("containers.id", ondelete="SET NULL"),
            nullable=True,
        ),
        # Phase 3 reservation. FK target table arrives later.
        sa.Column("runtime_deployment_id", GUID(), nullable=True),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uninstalled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    )
    # Partial unique on installed app_instances per project. The legacy
    # 0055 migration used postgresql_where only; SQLite gets a plain
    # unique index, which over-constrains across states but is acceptable
    # for desktop-mode single-installer scenarios.
    op.create_index(
        "uq_app_instance_project_installed",
        "app_instances",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("state = 'installed' AND project_id IS NOT NULL"),
    )
    op.create_index(
        "ix_app_instances_installer_state",
        "app_instances",
        ["installer_user_id", "state"],
    )
    op.create_index(
        "ix_app_instances_app_version_id", "app_instances", ["app_version_id"]
    )
    op.create_index("ix_app_instances_app_id", "app_instances", ["app_id"])

    # -----------------------------------------------------------------
    # STEP 8 — recreate app_install_attempts.
    # -----------------------------------------------------------------
    op.create_table(
        "app_install_attempts",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column(
            "marketplace_app_id",
            GUID(),
            sa.ForeignKey("marketplace_apps.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "app_version_id",
            GUID(),
            sa.ForeignKey("app_versions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "installer_user_id",
            GUID(),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "state", sa.String(32), nullable=False, server_default="hub_created"
        ),
        sa.Column("volume_id", sa.String(), nullable=True),
        sa.Column("node_name", sa.String(), nullable=True),
        sa.Column("bundle_hash", sa.String(), nullable=True),
        sa.Column(
            "app_instance_id",
            GUID(),
            sa.ForeignKey("app_instances.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reaped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
    )

    # -----------------------------------------------------------------
    # STEP 9 — re-attach FKs from existing tables to the new tables.
    # -----------------------------------------------------------------
    # spend_records.automation_run_id was added (FK-less) in 0073.
    with op.batch_alter_table("spend_records") as batch_op:
        batch_op.create_foreign_key(
            "fk_spend_records_automation_run_id_automation_runs",
            "automation_runs",
            ["automation_run_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_spend_records_app_instance_id_app_instances",
            "app_instances",
            ["app_instance_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("mcp_consent_records") as batch_op:
        batch_op.create_foreign_key(
            "fk_mcp_consent_records_app_instance_id_app_instances",
            "app_instances",
            ["app_instance_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("litellm_key_ledger") as batch_op:
        batch_op.create_foreign_key(
            "fk_litellm_key_ledger_app_instance_id_app_instances",
            "app_instances",
            ["app_instance_id"],
            ["id"],
            ondelete="SET NULL",
        )


# ---------------------------------------------------------------------------
# downgrade — intentionally partial.
# ---------------------------------------------------------------------------


def downgrade() -> None:
    """Partial downgrade: drops the new tables and reverses the column rename.

    Wiped data (legacy ``agent_schedules``, pre-reset ``app_instances``,
    matching ``spend_records`` rows, etc.) is NOT restored. Per the v8
    plan this migration is one-way.
    """
    # Drop FKs added in step 9 first so the new tables can be dropped.
    _drop_fks_to("litellm_key_ledger", "app_instances")
    _drop_fks_to("mcp_consent_records", "app_instances")
    _drop_fks_to("spend_records", "app_instances")
    _drop_fks_to("spend_records", "automation_runs")

    # Drop dependents-of-dependents first.
    op.drop_table("app_install_attempts")
    op.drop_table("app_instances")
    op.drop_table("app_automation_templates")
    op.drop_table("app_connector_requirements")
    op.drop_table("app_dependencies")
    op.drop_table("app_data_resources")
    op.drop_table("app_views")
    op.drop_index(
        "ix_automation_approval_requests_run_id",
        table_name="automation_approval_requests",
    )
    op.drop_table("automation_approval_requests")
    op.drop_index(
        "ix_automation_delivery_targets_automation_id",
        table_name="automation_delivery_targets",
    )
    op.drop_table("automation_delivery_targets")
    op.drop_index(
        "ix_automation_run_artifacts_run_id", table_name="automation_run_artifacts"
    )
    op.drop_table("automation_run_artifacts")
    op.drop_index(
        "ix_automation_runs_running_heartbeat", table_name="automation_runs"
    )
    op.drop_index(
        "ix_automation_runs_automation_status", table_name="automation_runs"
    )
    op.drop_table("automation_runs")
    op.drop_index(
        "uq_automation_events_idempotency_key", table_name="automation_events"
    )
    op.drop_index(
        "ix_automation_events_automation_received", table_name="automation_events"
    )
    op.drop_table("automation_events")
    op.drop_index(
        "ix_automation_actions_automation_id", table_name="automation_actions"
    )
    op.drop_table("automation_actions")
    op.drop_index("ix_app_actions_version_name", table_name="app_actions")
    op.drop_index("ix_app_actions_app_version_id", table_name="app_actions")
    op.drop_table("app_actions")
    op.drop_index(
        "ix_automation_triggers_cron_due", table_name="automation_triggers"
    )
    op.drop_index(
        "ix_automation_triggers_automation_id", table_name="automation_triggers"
    )
    op.drop_table("automation_triggers")
    op.drop_index(
        "ix_automation_definitions_team_id", table_name="automation_definitions"
    )
    op.drop_index(
        "ix_automation_definitions_owner_active",
        table_name="automation_definitions",
    )
    op.drop_table("automation_definitions")

    # Reverse the project_kind rename.
    op.drop_index("ix_projects_project_kind", table_name="projects")
    with op.batch_alter_table("projects") as batch_op:
        batch_op.drop_constraint("ck_projects_project_kind", type_="check")
        batch_op.alter_column(
            "project_kind",
            new_column_name="app_role",
            existing_type=sa.String(length=20),
            existing_nullable=False,
            server_default="none",
        )
    op.execute(
        sa.text("UPDATE projects SET app_role = 'none' WHERE app_role = 'workspace'")
    )
    op.execute(
        sa.text(
            "UPDATE projects SET app_role = 'app_instance' WHERE app_role = 'app_runtime'"
        )
    )
    op.create_index("ix_projects_app_role", "projects", ["app_role"])
