"""Install the ``automation_grants`` SQL VIEW.

Revision ID: 0082_automation_grants
Revises: 0081_cross_phase_cols
Create Date: 2026-04-26

This migration installs the read-only VIEW described in
``orchestrator/app/services/automations/grants_view.sql``. The VIEW unions
five existing permission tables (UserMcpConfig, McpConsentRecord,
ChannelConfig, DeploymentCredential, AppConnectorGrant) into the unified
Grant projection that ``grant_resolver.preflight_check()`` reads.

`contract.allowed_tools/skills/mcps/apps` lives inline on
AutomationDefinition.contract JSON and is read directly by
``grant_resolver.py`` — not part of the VIEW.

Portability
-----------
The VIEW uses Postgres-specific syntax (``jsonb_build_object``,
``::text`` casts, ``UNION ALL`` projections). SQLite installs (desktop
shell) skip view creation entirely — desktop runs without the unified
preflight surface today; the resolver gracefully degrades to per-table
lookups in the SQLite branch.

Down revision is ``0081_cross_phase_cols``.
"""

from collections.abc import Sequence
from pathlib import Path

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0082_automation_grants"
down_revision: str | Sequence[str] | None = "0081_cross_phase_cols"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Path to the canonical SQL spec lives next to the resolver code so it can
# be regenerated by hand without touching this migration file.
_VIEW_SQL_PATH = (
    Path(__file__).resolve().parents[2]
    / "app"
    / "services"
    / "automations"
    / "grants_view.sql"
)


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        # Desktop / SQLite: the VIEW is Postgres-only. The resolver detects
        # the dialect at query time and falls back to per-table lookups.
        return

    # asyncpg's prepared-statement protocol can't run multi-statement
    # strings, AND it can't tolerate ``;`` inside line-comments (the
    # comment text is part of the prepared statement). We strip line
    # comments first, then split on ``;``, then re-issue each statement
    # separately. The original commented SQL stays in ``grants_view.sql``
    # for humans to read; the server just gets the bare statements.
    raw = _VIEW_SQL_PATH.read_text()
    stripped = "\n".join(
        line for line in raw.splitlines()
        if not line.lstrip().startswith("--")
    )
    for chunk in stripped.split(";"):
        body = chunk.strip()
        if not body:
            continue
        op.execute(body + ";")


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return
    op.execute("DROP VIEW IF EXISTS automation_grants CASCADE")
