"""add browser_previews table

Revision ID: 0bbf9f52e450
Revises: 0768adba32a9
Create Date: 2025-12-08 20:57:33.609048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbf9f52e450'
down_revision: Union[str, Sequence[str], None] = '0768adba32a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create browser_previews table
    op.create_table('browser_previews',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('connected_container_id', sa.UUID(), nullable=True),
        sa.Column('position_x', sa.Float(), nullable=True, server_default='0'),
        sa.Column('position_y', sa.Float(), nullable=True, server_default='0'),
        sa.Column('current_path', sa.String(), nullable=True, server_default='/'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['connected_container_id'], ['containers.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_previews_id'), 'browser_previews', ['id'], unique=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_command_logs_user_id_fkey'), 'agent_command_logs', type_='foreignkey')
    op.drop_constraint(op.f('agent_command_logs_project_id_fkey'), 'agent_command_logs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_command_logs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agent_command_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('agent_reviews_agent_id_fkey'), 'agent_reviews', type_='foreignkey')
    op.drop_constraint(op.f('agent_reviews_user_id_fkey'), 'agent_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'agent_reviews', 'marketplace_agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agent_reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('base_reviews_base_id_fkey'), 'base_reviews', type_='foreignkey')
    op.drop_constraint(op.f('base_reviews_user_id_fkey'), 'base_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'base_reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'base_reviews', 'marketplace_bases', ['base_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chats_user_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_project_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('container_connections', 'connector_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.drop_constraint(op.f('container_connections_target_container_id_fkey'), 'container_connections', type_='foreignkey')
    op.drop_constraint(op.f('container_connections_source_container_id_fkey'), 'container_connections', type_='foreignkey')
    op.drop_constraint(op.f('container_connections_project_id_fkey'), 'container_connections', type_='foreignkey')
    op.create_foreign_key(None, 'container_connections', 'containers', ['source_container_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'container_connections', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'container_connections', 'containers', ['target_container_id'], ['id'], ondelete='CASCADE')
    op.alter_column('containers', 'deployment_mode',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.drop_constraint(op.f('containers_project_id_fkey'), 'containers', type_='foreignkey')
    op.drop_constraint(op.f('containers_base_id_fkey'), 'containers', type_='foreignkey')
    op.create_foreign_key(None, 'containers', 'marketplace_bases', ['base_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'containers', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('credit_purchases', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('credit_purchases_user_id_fkey'), 'credit_purchases', type_='foreignkey')
    op.create_foreign_key(None, 'credit_purchases', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('feedback_comments_user_id_fkey'), 'feedback_comments', type_='foreignkey')
    op.drop_constraint(op.f('feedback_comments_feedback_id_fkey'), 'feedback_comments', type_='foreignkey')
    op.create_foreign_key(None, 'feedback_comments', 'feedback_posts', ['feedback_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feedback_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('feedback_posts_user_id_fkey'), 'feedback_posts', type_='foreignkey')
    op.create_foreign_key(None, 'feedback_posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('feedback_upvotes_user_id_fkey'), 'feedback_upvotes', type_='foreignkey')
    op.drop_constraint(op.f('feedback_upvotes_feedback_id_fkey'), 'feedback_upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'feedback_upvotes', 'feedback_posts', ['feedback_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feedback_upvotes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('git_repositories_user_id_fkey'), 'git_repositories', type_='foreignkey')
    op.drop_constraint(op.f('git_repositories_project_id_fkey'), 'git_repositories', type_='foreignkey')
    op.create_foreign_key(None, 'git_repositories', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'git_repositories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('github_credentials_user_id_fkey'), 'github_credentials', type_='foreignkey')
    op.create_foreign_key(None, 'github_credentials', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('kanban_task_comments_user_id_fkey'), 'kanban_task_comments', type_='foreignkey')
    op.create_foreign_key(None, 'kanban_task_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('kanban_tasks_assignee_id_fkey'), 'kanban_tasks', type_='foreignkey')
    op.drop_constraint(op.f('kanban_tasks_reporter_id_fkey'), 'kanban_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'kanban_tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'kanban_tasks', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')
    op.alter_column('marketplace_transactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('marketplace_transactions', 'agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('marketplace_transactions_user_id_fkey'), 'marketplace_transactions', type_='foreignkey')
    op.drop_constraint(op.f('marketplace_transactions_creator_id_fkey'), 'marketplace_transactions', type_='foreignkey')
    op.drop_constraint(op.f('marketplace_transactions_agent_id_fkey'), 'marketplace_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'marketplace_transactions', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'marketplace_transactions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'marketplace_transactions', 'marketplace_agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_agents_user_id_fkey'), 'project_agents', type_='foreignkey')
    op.drop_constraint(op.f('project_agents_project_id_fkey'), 'project_agents', type_='foreignkey')
    op.drop_constraint(op.f('project_agents_agent_id_fkey'), 'project_agents', type_='foreignkey')
    op.create_foreign_key(None, 'project_agents', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_agents', 'marketplace_agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_agents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_assets_project_id_fkey'), 'project_assets', type_='foreignkey')
    op.create_foreign_key(None, 'project_assets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_files_project_id_fkey'), 'project_files', type_='foreignkey')
    op.create_foreign_key(None, 'project_files', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('projects', 'environment_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('shell_sessions_project_id_fkey'), 'shell_sessions', type_='foreignkey')
    op.drop_constraint(op.f('shell_sessions_user_id_fkey'), 'shell_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'shell_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shell_sessions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('usage_logs_project_id_fkey'), 'usage_logs', type_='foreignkey')
    op.drop_constraint(op.f('usage_logs_user_id_fkey'), 'usage_logs', type_='foreignkey')
    op.drop_constraint(op.f('usage_logs_agent_id_fkey'), 'usage_logs', type_='foreignkey')
    op.drop_constraint(op.f('usage_logs_creator_id_fkey'), 'usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'usage_logs', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'usage_logs', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'usage_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'usage_logs', 'marketplace_agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('user_api_keys_user_id_fkey'), 'user_api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'user_api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_custom_models_user_id_fkey'), 'user_custom_models', type_='foreignkey')
    op.create_foreign_key(None, 'user_custom_models', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_purchased_agents_user_id_fkey'), 'user_purchased_agents', type_='foreignkey')
    op.drop_constraint(op.f('user_purchased_agents_agent_id_fkey'), 'user_purchased_agents', type_='foreignkey')
    op.create_foreign_key(None, 'user_purchased_agents', 'marketplace_agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_purchased_agents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_purchased_bases_user_id_fkey'), 'user_purchased_bases', type_='foreignkey')
    op.drop_constraint(op.f('user_purchased_bases_base_id_fkey'), 'user_purchased_bases', type_='foreignkey')
    op.create_foreign_key(None, 'user_purchased_bases', 'marketplace_bases', ['base_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_purchased_bases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop browser_previews table
    op.drop_index(op.f('ix_browser_previews_id'), table_name='browser_previews')
    op.drop_table('browser_previews')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_purchased_bases', type_='foreignkey')
    op.drop_constraint(None, 'user_purchased_bases', type_='foreignkey')
    op.create_foreign_key(op.f('user_purchased_bases_base_id_fkey'), 'user_purchased_bases', 'marketplace_bases', ['base_id'], ['id'])
    op.create_foreign_key(op.f('user_purchased_bases_user_id_fkey'), 'user_purchased_bases', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_purchased_agents', type_='foreignkey')
    op.drop_constraint(None, 'user_purchased_agents', type_='foreignkey')
    op.create_foreign_key(op.f('user_purchased_agents_agent_id_fkey'), 'user_purchased_agents', 'marketplace_agents', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('user_purchased_agents_user_id_fkey'), 'user_purchased_agents', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_custom_models', type_='foreignkey')
    op.create_foreign_key(op.f('user_custom_models_user_id_fkey'), 'user_custom_models', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('user_api_keys_user_id_fkey'), 'user_api_keys', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.create_foreign_key(op.f('usage_logs_creator_id_fkey'), 'usage_logs', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(op.f('usage_logs_agent_id_fkey'), 'usage_logs', 'marketplace_agents', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('usage_logs_user_id_fkey'), 'usage_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('usage_logs_project_id_fkey'), 'usage_logs', 'projects', ['project_id'], ['id'])
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'shell_sessions', type_='foreignkey')
    op.drop_constraint(None, 'shell_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('shell_sessions_user_id_fkey'), 'shell_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('shell_sessions_project_id_fkey'), 'shell_sessions', 'projects', ['project_id'], ['id'])
    op.alter_column('projects', 'environment_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'project_files', type_='foreignkey')
    op.create_foreign_key(op.f('project_files_project_id_fkey'), 'project_files', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_assets', type_='foreignkey')
    op.create_foreign_key(op.f('project_assets_project_id_fkey'), 'project_assets', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_agents', type_='foreignkey')
    op.drop_constraint(None, 'project_agents', type_='foreignkey')
    op.drop_constraint(None, 'project_agents', type_='foreignkey')
    op.create_foreign_key(op.f('project_agents_agent_id_fkey'), 'project_agents', 'marketplace_agents', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('project_agents_project_id_fkey'), 'project_agents', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_agents_user_id_fkey'), 'project_agents', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'marketplace_transactions', type_='foreignkey')
    op.drop_constraint(None, 'marketplace_transactions', type_='foreignkey')
    op.drop_constraint(None, 'marketplace_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('marketplace_transactions_agent_id_fkey'), 'marketplace_transactions', 'marketplace_agents', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('marketplace_transactions_creator_id_fkey'), 'marketplace_transactions', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(op.f('marketplace_transactions_user_id_fkey'), 'marketplace_transactions', 'users', ['user_id'], ['id'])
    op.alter_column('marketplace_transactions', 'agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('marketplace_transactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'kanban_tasks', type_='foreignkey')
    op.drop_constraint(None, 'kanban_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('kanban_tasks_reporter_id_fkey'), 'kanban_tasks', 'users', ['reporter_id'], ['id'])
    op.create_foreign_key(op.f('kanban_tasks_assignee_id_fkey'), 'kanban_tasks', 'users', ['assignee_id'], ['id'])
    op.drop_constraint(None, 'kanban_task_comments', type_='foreignkey')
    op.create_foreign_key(op.f('kanban_task_comments_user_id_fkey'), 'kanban_task_comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'github_credentials', type_='foreignkey')
    op.create_foreign_key(op.f('github_credentials_user_id_fkey'), 'github_credentials', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'git_repositories', type_='foreignkey')
    op.drop_constraint(None, 'git_repositories', type_='foreignkey')
    op.create_foreign_key(op.f('git_repositories_project_id_fkey'), 'git_repositories', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('git_repositories_user_id_fkey'), 'git_repositories', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'feedback_upvotes', type_='foreignkey')
    op.drop_constraint(None, 'feedback_upvotes', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_upvotes_feedback_id_fkey'), 'feedback_upvotes', 'feedback_posts', ['feedback_id'], ['id'])
    op.create_foreign_key(op.f('feedback_upvotes_user_id_fkey'), 'feedback_upvotes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'feedback_posts', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_posts_user_id_fkey'), 'feedback_posts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'feedback_comments', type_='foreignkey')
    op.drop_constraint(None, 'feedback_comments', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_comments_feedback_id_fkey'), 'feedback_comments', 'feedback_posts', ['feedback_id'], ['id'])
    op.create_foreign_key(op.f('feedback_comments_user_id_fkey'), 'feedback_comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'credit_purchases', type_='foreignkey')
    op.create_foreign_key(op.f('credit_purchases_user_id_fkey'), 'credit_purchases', 'users', ['user_id'], ['id'])
    op.alter_column('credit_purchases', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.create_foreign_key(op.f('containers_base_id_fkey'), 'containers', 'marketplace_bases', ['base_id'], ['id'])
    op.create_foreign_key(op.f('containers_project_id_fkey'), 'containers', 'projects', ['project_id'], ['id'])
    op.alter_column('containers', 'deployment_mode',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'container'::character varying"),
               nullable=False)
    op.drop_constraint(None, 'container_connections', type_='foreignkey')
    op.drop_constraint(None, 'container_connections', type_='foreignkey')
    op.drop_constraint(None, 'container_connections', type_='foreignkey')
    op.create_foreign_key(op.f('container_connections_project_id_fkey'), 'container_connections', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('container_connections_source_container_id_fkey'), 'container_connections', 'containers', ['source_container_id'], ['id'])
    op.create_foreign_key(op.f('container_connections_target_container_id_fkey'), 'container_connections', 'containers', ['target_container_id'], ['id'])
    op.alter_column('container_connections', 'connector_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'env_injection'::character varying"),
               nullable=False)
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_project_id_fkey'), 'chats', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('chats_user_id_fkey'), 'chats', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'base_reviews', type_='foreignkey')
    op.drop_constraint(None, 'base_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('base_reviews_user_id_fkey'), 'base_reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('base_reviews_base_id_fkey'), 'base_reviews', 'marketplace_bases', ['base_id'], ['id'])
    op.drop_constraint(None, 'agent_reviews', type_='foreignkey')
    op.drop_constraint(None, 'agent_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('agent_reviews_user_id_fkey'), 'agent_reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('agent_reviews_agent_id_fkey'), 'agent_reviews', 'marketplace_agents', ['agent_id'], ['id'])
    op.drop_constraint(None, 'agent_command_logs', type_='foreignkey')
    op.drop_constraint(None, 'agent_command_logs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_command_logs_project_id_fkey'), 'agent_command_logs', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('agent_command_logs_user_id_fkey'), 'agent_command_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
