"""
Content-addressable bundle storage.

Three adapters:
- `LocalBundleStorage` — writes bytes to `BUNDLE_STORAGE_DIR/{kind}/{slug}/{version}.tar.zst`.
  The signed download URL is generated by HMAC-ing (path, expires_at) with
  `BUNDLE_URL_SECRET` and exposed as `?sig=…&exp=…`. The `/v1/bundles/...`
  download endpoint verifies the signature before streaming.
- `S3BundleStorage` — boto3-shaped uploads + presigned GET URLs.
- `VolumeHubBundleStorage` — gRPC bridge to the OpenSail Volume Hub. Returns a
  `NotImplementedError` if `VOLUME_HUB_URL` isn't set; this is the documented
  Wave 7 placeholder.

All adapters return a `BundleRef` (storage_key + sha256 + size_bytes), and a
separate `signed_url(...)` call returns the time-limited URL for the bundle
envelope.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import logging
import os
import secrets
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol
from urllib.parse import quote, urlencode

from ..config import Settings, get_settings

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class BundleRef:
    """Result of a bundle put.

    `storage_key` is opaque to callers — the adapter knows how to read it back.
    """

    storage_key: str
    sha256: str
    size_bytes: int
    backend: str


class BundleStorage(Protocol):
    """Adapter contract."""

    backend_name: str

    def put_bytes(self, kind: str, slug: str, version: str, data: bytes) -> BundleRef: ...

    def open_stream(self, storage_key: str): ...

    def signed_url(self, kind: str, slug: str, version: str, storage_key: str) -> tuple[str, int]: ...

    def head(self, storage_key: str) -> dict[str, int | str]: ...


# ---------------------------------------------------------------------------
# Local FS adapter
# ---------------------------------------------------------------------------


def _ensure_secret(settings: Settings) -> str:
    """Return BUNDLE_URL_SECRET, generating + persisting one on first boot."""
    if settings.bundle_url_secret:
        return settings.bundle_url_secret

    # Persist alongside the hub_id file so a fresh service deploy keeps a
    # stable secret even when env-vars are unset.
    cache_path = Path(settings.bundle_storage_dir).expanduser() / ".bundle_url_secret"
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    if cache_path.exists():
        text = cache_path.read_text(encoding="utf-8").strip()
        if text:
            settings.bundle_url_secret = text
            return text

    secret = secrets.token_urlsafe(48)
    tmp = cache_path.with_suffix(cache_path.suffix + ".tmp")
    tmp.write_text(secret, encoding="utf-8")
    os.chmod(tmp, 0o600)
    os.replace(tmp, cache_path)
    settings.bundle_url_secret = secret
    logger.info("generated bundle URL signing secret at %s", cache_path)
    return secret


def _safe_segment(value: str) -> str:
    """Normalise a path segment to allowed characters only."""
    safe = "".join(c if c.isalnum() or c in ("-", "_", ".") else "_" for c in value)
    if not safe or safe in (".", ".."):
        raise ValueError(f"invalid storage path segment: {value!r}")
    return safe


class LocalBundleStorage:
    """Writes bundles to the local filesystem and signs URLs back at /v1/bundles."""

    backend_name = "local"

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._root = Path(settings.bundle_storage_dir).expanduser().resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def _abs_path(self, relative_key: str) -> Path:
        candidate = (self._root / relative_key).resolve()
        if not str(candidate).startswith(str(self._root)):
            raise ValueError(f"storage_key escapes bundle root: {relative_key}")
        return candidate

    def put_bytes(self, kind: str, slug: str, version: str, data: bytes) -> BundleRef:
        rel_dir = Path(_safe_segment(kind)) / _safe_segment(slug)
        filename = f"{_safe_segment(version)}.tar.zst"
        full_dir = (self._root / rel_dir).resolve()
        full_dir.mkdir(parents=True, exist_ok=True)
        full_path = full_dir / filename
        tmp_path = full_path.with_suffix(full_path.suffix + ".tmp")
        tmp_path.write_bytes(data)
        os.replace(tmp_path, full_path)
        digest = hashlib.sha256(data).hexdigest()
        size = len(data)
        relative_key = f"{rel_dir.as_posix()}/{filename}"
        return BundleRef(storage_key=relative_key, sha256=digest, size_bytes=size, backend=self.backend_name)

    def open_stream(self, storage_key: str):
        return self._abs_path(storage_key).open("rb")

    def head(self, storage_key: str) -> dict[str, int | str]:
        path = self._abs_path(storage_key)
        if not path.exists():
            raise FileNotFoundError(storage_key)
        return {"size_bytes": path.stat().st_size, "storage_key": storage_key}

    # -----------------------------------------------------------------
    # URL signing
    # -----------------------------------------------------------------

    def signed_url(self, kind: str, slug: str, version: str, storage_key: str) -> tuple[str, int]:
        secret = _ensure_secret(self._settings)
        ttl = self._settings.bundle_url_ttl_seconds
        expires_at = int(time.time()) + ttl
        path = f"/v1/bundles/{quote(kind)}/{quote(slug)}/{quote(version)}"
        # Sign the (path, exp) tuple — the storage_key isn't included so URL
        # rotation is a no-op when we re-emit a bundle.
        sig_bytes = hmac.new(
            secret.encode("utf-8"),
            f"{path}\n{expires_at}".encode("utf-8"),
            hashlib.sha256,
        ).digest()
        sig = base64.urlsafe_b64encode(sig_bytes).rstrip(b"=").decode("ascii")
        params = urlencode({"exp": expires_at, "sig": sig})
        url = f"{self._settings.bundle_base_url.rstrip('/')}{path}?{params}"
        return url, expires_at

    def verify_signed_url(
        self, kind: str, slug: str, version: str, expires_at: int, signature: str
    ) -> bool:
        if expires_at < int(time.time()):
            return False
        secret = _ensure_secret(self._settings)
        path = f"/v1/bundles/{quote(kind)}/{quote(slug)}/{quote(version)}"
        sig_bytes = hmac.new(
            secret.encode("utf-8"),
            f"{path}\n{expires_at}".encode("utf-8"),
            hashlib.sha256,
        ).digest()
        expected = base64.urlsafe_b64encode(sig_bytes).rstrip(b"=").decode("ascii")
        return hmac.compare_digest(expected, signature)


# ---------------------------------------------------------------------------
# S3 adapter — boto3 shape, no hard dep at import time
# ---------------------------------------------------------------------------


class S3BundleStorage:
    """S3-backed bundle storage. Lazily imports boto3."""

    backend_name = "s3"

    def __init__(self, settings: Settings) -> None:
        if not settings.s3_bucket:
            raise RuntimeError("BUNDLE_STORAGE_BACKEND=s3 requires S3_BUCKET")
        try:
            import boto3  # type: ignore[import-not-found]
        except ImportError as exc:
            raise RuntimeError(
                "S3 bundle storage requires the optional `boto3` dependency"
            ) from exc

        self._settings = settings
        self._bucket = settings.s3_bucket
        kwargs: dict = {}
        if settings.s3_region:
            kwargs["region_name"] = settings.s3_region
        if settings.s3_endpoint_url:
            kwargs["endpoint_url"] = settings.s3_endpoint_url
        self._client = boto3.client("s3", **kwargs)

    def _key_for(self, kind: str, slug: str, version: str) -> str:
        return f"{_safe_segment(kind)}/{_safe_segment(slug)}/{_safe_segment(version)}.tar.zst"

    def put_bytes(self, kind: str, slug: str, version: str, data: bytes) -> BundleRef:
        key = self._key_for(kind, slug, version)
        self._client.put_object(
            Bucket=self._bucket,
            Key=key,
            Body=data,
            ContentType="application/zstd",
        )
        return BundleRef(
            storage_key=key,
            sha256=hashlib.sha256(data).hexdigest(),
            size_bytes=len(data),
            backend=self.backend_name,
        )

    def open_stream(self, storage_key: str):
        obj = self._client.get_object(Bucket=self._bucket, Key=storage_key)
        return obj["Body"]

    def head(self, storage_key: str) -> dict[str, int | str]:
        head = self._client.head_object(Bucket=self._bucket, Key=storage_key)
        return {"size_bytes": head["ContentLength"], "storage_key": storage_key}

    def signed_url(self, kind: str, slug: str, version: str, storage_key: str) -> tuple[str, int]:
        ttl = self._settings.bundle_url_ttl_seconds
        url = self._client.generate_presigned_url(
            "get_object",
            Params={"Bucket": self._bucket, "Key": storage_key},
            ExpiresIn=ttl,
        )
        return url, int(time.time()) + ttl


# ---------------------------------------------------------------------------
# Volume Hub adapter — gRPC bridge for the OpenSail Volume Hub.
# Wave-7 documented placeholder; raises NotImplementedError if no URL set.
# ---------------------------------------------------------------------------


class VolumeHubBundleStorage:
    """Fronts the OpenSail Volume Hub for app-bundle CAS reads."""

    backend_name = "volume_hub"

    def __init__(self, settings: Settings) -> None:
        if not settings.volume_hub_url:
            raise NotImplementedError(
                "Volume Hub adapter requires VOLUME_HUB_URL; not yet wired in this build"
            )
        self._settings = settings
        self._endpoint = settings.volume_hub_url.rstrip("/")

    def put_bytes(self, kind: str, slug: str, version: str, data: bytes) -> BundleRef:
        raise NotImplementedError("Volume Hub put is owned by the orchestrator-side publisher")

    def open_stream(self, storage_key: str):
        raise NotImplementedError("Volume Hub stream reads are out of scope for the marketplace service")

    def head(self, storage_key: str) -> dict[str, int | str]:
        raise NotImplementedError("head not implemented for Volume Hub adapter")

    def signed_url(self, kind: str, slug: str, version: str, storage_key: str) -> tuple[str, int]:
        # In production this asks Volume Hub for a pre-signed S3 URL via gRPC.
        # We keep the method available so the rest of the pipeline doesn't
        # branch on backend; orchestrators that opt into this backend deploy
        # the gRPC client wiring out-of-band.
        raise NotImplementedError(
            "Volume Hub signed URL generation requires the gRPC client; not enabled in this build"
        )


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------


_storage: BundleStorage | None = None


def get_bundle_storage(settings: Settings | None = None) -> BundleStorage:
    global _storage
    if _storage is not None:
        return _storage
    settings = settings or get_settings()
    backend = settings.bundle_storage_backend.lower()
    if backend == "local":
        _storage = LocalBundleStorage(settings)
    elif backend == "s3":
        _storage = S3BundleStorage(settings)
    elif backend == "volume_hub":
        _storage = VolumeHubBundleStorage(settings)
    else:
        raise RuntimeError(f"unknown BUNDLE_STORAGE_BACKEND={backend!r}")
    return _storage


def reset_bundle_storage_cache() -> None:
    global _storage
    _storage = None
