"""
Test-only helper endpoints.

Registered ONLY when env var TEST_HELPERS_ENABLED=1. Provides a way for
end-to-end tests (Playwright) to capture magic-link emails that were sent in
dev-mode fallback (SMTP not configured) so the flow can be exercised without
real email delivery.

Security: the entire router is gated by an environment variable. Production
deployments never set this flag, so the endpoint doesn't exist at runtime.
Even if accidentally enabled, it only exposes magic-link codes that were
generated by this backend instance — which is the exact information that was
just emailed to the user.
"""

from __future__ import annotations

import os
from collections import defaultdict
from typing import Any

from fastapi import APIRouter, HTTPException, status

router = APIRouter()


def is_enabled() -> bool:
    return os.environ.get("TEST_HELPERS_ENABLED", "").lower() in ("1", "true", "yes")


# In-memory captured outbox: {email: [{link_url, code}, ...]}
# Populated by EmailService.send_magic_link when SMTP isn't configured AND
# test helpers are enabled.
_captured_inbox: dict[str, list[dict[str, Any]]] = defaultdict(list)


def capture(to_email: str, link_url: str, code: str) -> None:
    """Called from EmailService fallback path when test helpers are enabled."""
    if not is_enabled():
        return
    _captured_inbox[to_email.lower()].append({"link_url": link_url, "code": code})


@router.get("/magic-link-inbox")
async def magic_link_inbox(email: str) -> dict[str, Any]:
    """
    Pop the OLDEST captured magic-link entry for an email (FIFO).

    Returns `{found: false}` when the inbox is empty. Each call removes one
    entry, so callers can drain the inbox with repeated GETs — useful for
    rate-limit tests that need to verify "exactly N emails were sent".

    For convenience, the latest entry's fields (`link_url`, `code`) are
    spread into the top-level response so simple tests can read them
    without indexing. `remaining` reports the count left after this pop.
    """
    if not is_enabled():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Not Found")
    entries = _captured_inbox.get(email.lower(), [])
    if not entries:
        return {"found": False, "remaining": 0}
    # FIFO pop — the first one captured is the first one returned.
    oldest = entries.pop(0)
    return {"found": True, "remaining": len(entries), **oldest}
