/**
 * PDF generator for intake form submissions.
 * Uses pdfkit to produce a Buffer from an IntakeSubmission.
 */
import type { IntakeSubmission } from "@/lib/types";

export async function generateIntakePdf(
  submission: IntakeSubmission
): Promise<Buffer> {
  // Dynamically import pdfkit so it works in Next.js edge-aware environments
  const PDFDocument = (await import("pdfkit")).default;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "LETTER" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // ── Header ─────────────────────────────────────────────────────────────
    doc
      .font("Helvetica-Bold")
      .fontSize(20)
      .text("Legal Intake Form — Submission Record", { align: "center" });

    doc.moveDown(0.5);
    doc
      .font("Helvetica")
      .fontSize(10)
      .fillColor("#666666")
      .text(`Submission ID: ${submission.id}`, { align: "center" })
      .text(
        `Submitted: ${new Date(submission.submitted_at).toLocaleString("en-US", {
          dateStyle: "full",
          timeStyle: "short",
        })}`,
        { align: "center" }
      );

    doc.fillColor("#000000").moveDown(1);
    doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor("#CCCCCC").stroke();
    doc.moveDown(1);

    // ── Helper ─────────────────────────────────────────────────────────────
    function field(label: string, value: string | undefined | null) {
      doc.font("Helvetica-Bold").fontSize(10).text(`${label}:`, { continued: true });
      doc
        .font("Helvetica")
        .fontSize(10)
        .text(` ${value ?? "—"}`, { continued: false });
      doc.moveDown(0.4);
    }

    // ── Client Information ──────────────────────────────────────────────────
    doc.font("Helvetica-Bold").fontSize(13).text("Client Information");
    doc.moveDown(0.5);

    field("Full Name", `${submission.first_name} ${submission.last_name}`);
    field("Email", submission.email);
    field("Phone", submission.phone ?? "Not provided");

    doc.moveDown(0.6);
    doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor("#EEEEEE").stroke();
    doc.moveDown(0.8);

    // ── Matter Details ──────────────────────────────────────────────────────
    doc.font("Helvetica-Bold").fontSize(13).text("Matter Details");
    doc.moveDown(0.5);

    field("Matter Type", submission.matter_type);

    doc.font("Helvetica-Bold").fontSize(10).text("Description:");
    doc.font("Helvetica").fontSize(10).text(submission.description, {
      width: 512,
      lineGap: 3,
    });
    doc.moveDown(0.8);

    doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor("#EEEEEE").stroke();
    doc.moveDown(0.8);

    // ── Uploaded Files ──────────────────────────────────────────────────────
    doc.font("Helvetica-Bold").fontSize(13).text("Uploaded Files");
    doc.moveDown(0.5);

    const files = submission.uploaded_file_refs ?? [];
    if (files.length === 0) {
      doc.font("Helvetica").fontSize(10).text("No files uploaded.");
    } else {
      files.forEach((f, i) => {
        const sizeMb = (f.size / (1024 * 1024)).toFixed(2);
        doc
          .font("Helvetica")
          .fontSize(10)
          .text(`${i + 1}. ${f.name}  (${sizeMb} MB, ${f.mime})`);
      });
    }

    doc.moveDown(0.8);
    doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor("#EEEEEE").stroke();
    doc.moveDown(0.8);

    // ── Consent ─────────────────────────────────────────────────────────────
    doc.font("Helvetica-Bold").fontSize(13).text("Consent");
    doc.moveDown(0.5);
    field(
      "Client consented to data processing",
      submission.consent ? "Yes ✓" : "No ✗"
    );

    // ── Footer ──────────────────────────────────────────────────────────────
    doc.moveDown(2);
    doc
      .font("Helvetica")
      .fontSize(8)
      .fillColor("#999999")
      .text(
        "This document was automatically generated by the Legal Intake System. " +
          "It is a confidential record and should not be distributed outside the firm.",
        { align: "center", width: 512 }
      );

    doc.end();
  });
}
